// Redux store and hooks
export { store, useAppDispatch, useAppSelector } from "./store";
export type { RootState, AppDispatch } from "./store";

export {
  selectActiveSourceId,
  selectConnectionSnapshot,
  selectSdrControls,
  selectSourceInventory,
  selectSpectrumControls,
} from "./selectors/spectrumSelectors";

export {
  setSourceBinding,
  setSourceBindings,
  clearSourceBindings,
  setSourceSelectionMode,
  sourceBindingKey,
} from "./slices/sourceRoutingSlice";

export {
  setSelectedSourceId,
  setSelectionIntentSourceId,
  setPendingSourceSwitchId,
  clearSelectedSourceId,
} from "./slices/sourceSelectionSlice";

// Export slice actions
export {
  setAuthenticating,
  setAuthSuccess,
  setAuthFailed,
  setAuthReady,
  setHasPasskeys,
  setPasskeyRegistrationSuccess,
  clearSession,
  resetAuth,
  setInitialAuthCheckComplete,
} from "./slices/authSlice";

// Import auth actions for collective export
import {
  setAuthenticating,
  setAuthSuccess,
  setAuthFailed,
  setAuthReady,
  setHasPasskeys,
  setPasskeyRegistrationSuccess,
  clearSession,
  resetAuth,
  setInitialAuthCheckComplete,
} from "./slices/authSlice";

// Export collective action objects for convenience
export const authActions = {
  setAuthenticating,
  setAuthSuccess,
  setAuthFailed,
  setAuthReady,
  setHasPasskeys,
  setPasskeyRegistrationSuccess,
  clearSession,
  resetAuth,
  setInitialAuthCheckComplete,
};

export {
  createNoteCardFromSpectrum,
  hydrateNoteCards,
  updateNoteCardText,
  updateNoteCardPosition,
  updateNoteCardSize,
  attachNoteCardSnapshot,
  setActiveNoteCard,
  removeNoteCard,
  clearNoteCards,
  setNoteCardsCollapsed,
} from "./slices/noteCardsSlice";

export {
  loadPersistedNoteCards,
  persistNoteCards,
  clearPersistedNoteCards,
} from "@n-apt/app/infrastructure/services/noteCardStorage";

export {
  selectNoteCards,
  selectActiveNoteCard,
  selectNoteCardsCollapsed,
} from "./slices/noteCardsSlice";

// Import spectrum actions for collective export
import {
  setFrequencyRange,
  setActiveSignalArea,
  setSignalAreaAndRange,
  tuneToChannels,
  mergeLastKnownRanges,
  setVizZoom,
  setMaxVizZoom,
  setVizZoomFloor,
  setVizZoomFloorPan,
  setAutoZoomStability,
  setVizPan,
  setDisplayMode,
  setFftDbLimits,
  setFftSize,
  setFftSizeOptions,
  setFftWindow,
  setFftFrameRate,
  setFftAvgEnabled,
  setFftSmoothEnabled,
  setWfSmoothEnabled,
  setTxSignal,
  setTxSampleRateHz,
  setTxIfftSize,
  setTxViewerSampleRateHz,
  setTxViewerFftSize,
  setTxViewerFftFrameRate,
  setTxViewerFftWindow,
  setTxViewerTemporalResolution,
  setTxViewerPowerScale,
  setTxCenterFrequencyHz,
  setTxGeometry,
  setDeviceKind,
  setTxPowerDbm,
  setTxVgaGain,
  setTxSafetyEnabled,
  setTxSafetyLimit,
  setTxHopType,
  setTxHopStartFrequencyHz,
  setTxHopEndFrequencyHz,
  setTxHopChannels,
  setTxHopRateHz,
  setTxHopEnabled,
  setGain,
  setHackrfLnaGain,
  setHackrfVgaGain,
  setHackrfAmpEnabled,
  setPpm,
  setTunerAGC,
  setRtlAGC,
  setSampleRate,
  setSdrSettingsBundle,
  setBasebandFilterPinned,
  setVisualizerPaused,
  setDetectedFrameRate,
  setDiagnosticStatus,
  setDiagnosticRunning,
  triggerDiagnostic,
  resetZoomAndDb,
  resetLiveControls,
  setTemporalResolution,
  setPowerScale,
  setMinReceiveSampleRate,
  setShowSpikeOverlay,
  setRemoveDcSpike,
  setGpuSpikeCount,
  setShowTxSlider,
  setStitchOption,
  setStitchOptionValue,
} from "./slices/spectrumSlice";

// Export spectrum actions as individual
export {
  setFrequencyRange,
  setActiveSignalArea,
  setSignalAreaAndRange,
  tuneToChannels,
  mergeLastKnownRanges,
  setVizZoom,
  setMaxVizZoom,
  setVizZoomFloor,
  setVizZoomFloorPan,
  setAutoZoomStability,
  setVizPan,
  setDisplayMode,
  setFftDbLimits,
  setFftSize,
  setFftSizeOptions,
  setFftWindow,
  setFftFrameRate,
  setFftAvgEnabled,
  setFftSmoothEnabled,
  setWfSmoothEnabled,
  setTxSignal,
  setTxSampleRateHz,
  setTxIfftSize,
  setTxViewerSampleRateHz,
  setTxViewerFftSize,
  setTxViewerFftFrameRate,
  setTxViewerFftWindow,
  setTxViewerTemporalResolution,
  setTxViewerPowerScale,
  setTxCenterFrequencyHz,
  setTxGeometry,
  setDeviceKind,
  setTxPowerDbm,
  setTxVgaGain,
  setTxSafetyEnabled,
  setTxSafetyLimit,
  setTxHopType,
  setTxHopStartFrequencyHz,
  setTxHopEndFrequencyHz,
  setTxHopChannels,
  setTxHopRateHz,
  setTxHopEnabled,
  setGain,
  setHackrfLnaGain,
  setHackrfVgaGain,
  setHackrfAmpEnabled,
  setPpm,
  setTunerAGC,
  setRtlAGC,
  setSampleRate,
  setSdrSettingsBundle,
  setBasebandFilterPinned,
  setVisualizerPaused,
  setDetectedFrameRate,
  setDiagnosticStatus,
  setDiagnosticRunning,
  triggerDiagnostic,
  resetZoomAndDb,
  resetLiveControls,
  setTemporalResolution,
  setPowerScale,
  setMinReceiveSampleRate,
  setShowSpikeOverlay,
  setRemoveDcSpike,
  setGpuSpikeCount,
  setShowTxSlider,
  setStitchOption,
  setStitchOptionValue,
} from "./slices/spectrumSlice";

// Export collective action objects for convenience
export const spectrumActions = {
  setFrequencyRange,
  setActiveSignalArea,
  setSignalAreaAndRange,
  tuneToChannels,
  mergeLastKnownRanges,
  setVizZoom,
  setMaxVizZoom,
  setVizZoomFloor,
  setVizZoomFloorPan,
  setAutoZoomStability,
  setVizPan,
  setDisplayMode,
  setFftDbLimits,
  setFftSize,
  setFftSizeOptions,
  setFftWindow,
  setFftFrameRate,
  setFftAvgEnabled,
  setFftSmoothEnabled,
  setWfSmoothEnabled,
  setTxSignal,
  setTxSampleRateHz,
  setTxIfftSize,
  setTxViewerSampleRateHz,
  setTxViewerFftSize,
  setTxViewerFftFrameRate,
  setTxViewerFftWindow,
  setTxViewerTemporalResolution,
  setTxViewerPowerScale,
  setTxCenterFrequencyHz,
  setTxGeometry,
  setDeviceKind,
  setTxPowerDbm,
  setTxVgaGain,
  setTxSafetyEnabled,
  setTxSafetyLimit,
  setTxHopType,
  setTxHopStartFrequencyHz,
  setTxHopEndFrequencyHz,
  setTxHopChannels,
  setTxHopRateHz,
  setTxHopEnabled,
  setGain,
  setHackrfLnaGain,
  setHackrfVgaGain,
  setHackrfAmpEnabled,
  setPpm,
  setTunerAGC,
  setRtlAGC,
  setSampleRate,
  setSdrSettingsBundle,
  setBasebandFilterPinned,
  setVisualizerPaused,
  setDiagnosticStatus,
  setDiagnosticRunning,
  triggerDiagnostic,
  resetZoomAndDb,
  resetLiveControls,
  setTemporalResolution,
  setPowerScale,
  setShowSpikeOverlay,
  setRemoveDcSpike,
  setGpuSpikeCount,
  setShowTxSlider,
};

export {
  setSourceMode,
  setSelectedFiles,
  setFileMetadata,
  setDrawSignal3D,
  setStitchPaused,
  setStitchStatus,
  setStitchSourceSettings,
  setActivePlaybackMetadata,
  setPlaybackChannels,
  clearActivePlaybackMetadata,
  incrementPlaybackFrameCounter,
  triggerStitch,
  toggleStitchPause,
  resetDrawParams,
  resetTrainingCapture,
  setGlobalNoiseFloor,
  clearWaterfall,
  resetWaterfallCleared,
  setDrawParams,
  setClumpParams,
  setActiveClumpIndex,
} from "./slices/waterfallSlice";

export {
  setAppMode,
  setAccentColor,
  setFftColor,
  setWaterfallTheme,
  resetTheme,
} from "./slices/themeSlice";

export {
  setSnapshotProgress,
  clearSnapshotProgress,
  bumpSnapshotSectionPulse,
} from "./slices/snapshotSlice";

// Import theme actions for collective export
import {
  setAppMode,
  setAccentColor,
  setFftColor,
  setWaterfallTheme,
  resetTheme,
  updateThemeSettings,
} from "./slices/themeSlice";

// Export collective action objects for convenience
export const themeActions = {
  setAppMode,
  setAccentColor,
  setFftColor,
  setWaterfallTheme,
  resetTheme,
  updateThemeSettings,
};

export {
  setSnapshotGrid,
  setMirrorIqBasebandBelowZero,
  setDeviceInfo,
  resetSettings,
} from "./slices/settingsSlice";

// Import websocket actions for collective export
import {
  setConnecting,
  setConnected,
  setDisconnected,
  setReconnecting,
  setError,
  setOperationalError,
  updateDeviceState,
  setCaptureStatus,
  setSpectrumFrames,
  setPaused,
  setCryptoCorrupted,
} from "./slices/websocketSlice";

export {
  setConnecting,
  setConnected,
  setDisconnected,
  setReconnecting,
  setError,
  setOperationalError,
  updateDeviceState,
  setCaptureStatus,
  setSpectrumFrames,
  setPaused,
  setCryptoCorrupted,
} from "./slices/websocketSlice";

// Export collective action objects for convenience
export const websocketActions = {
  setConnecting,
  setConnected,
  setDisconnected,
  setReconnecting,
  setError,
  setOperationalError,
  updateDeviceState,
  setCaptureStatus,
  setSpectrumFrames,
  setPaused,
  setCryptoCorrupted,
};

// Export thunks - explicit exports to prevent Safari issues
export {
  connectWebSocket,
  disconnectWebSocket,
  sendFrequencyRange,
  sendCenterFrequency,
  sendPauseCommand,
  sendSettings,
  sendRestartDevice,
  sendTrainingCommand,
  sendPowerScaleCommand,
  sendCaptureCommand,
  sendCaptureStopCommand,
  sendScanCommand,
  sendDemodulateCommand,
  toggleVisualizerPause,
} from "./thunks/websocketThunks";

// Export selectors - explicit exports to prevent Safari issues
export {
  selectAuthState,
  selectSpectrumState,
  selectWaterfallState,
  selectThemeState,
  selectSettingsState,
  selectWebSocketState,
  selectIsAuthenticated,
  selectAuthError,
  selectSessionToken,
  selectHasPasskeys,
  selectFrequencyRange,
  selectActiveSignalArea,
  selectAnalysisViewState,
  selectPowerScale,
  selectFftSettings,
  selectVisualizationSettings,
  selectSdrSettings,
  selectDrawParams,
  selectDrawSignalState,
  selectSourceMode,
  selectSelectedSourceId,
  selectSourceSelectionLifecycle,
  selectSourceTransportSnapshot,
  selectActiveDrawParams,
  selectTrainingCaptureState,
  selectStitchState,
  selectThemeColors,
  selectConnectionState,
  selectDeviceState,
  selectDeviceSettings,
  selectSpectrumData,
  selectEffectiveFrequencyRange,
  selectSampleRateHz,
  selectSignalAreaBounds,
  selectIsVisualizerRouteActive,
  selectThemeObject,
  selectHighFrequencyData,
  selectIsWebSocketReady,
  selectDeviceCapabilities,
  selectSourceDerivedState,
  selectActiveSourceDerivedState,
} from "./selectors/performanceSelectors";

// Export middleware (for advanced usage)
export { default as websocketMiddleware } from "./middleware/websocketMiddleware";
export { default as localStorageMiddleware } from "./middleware/localStorageMiddleware";

// Export persistence helpers
export {
  loadPersistedTheme,
  loadPersistedSdrSettings,
  loadPersistedPasskeys,
  loadPersistedSpectrumFrames,
  loadPersistedSignalsDefaults,
} from "./middleware/localStorageMiddleware";
