// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function isOpen(ws) {
  return ws.readyState === 1;
}

var $$WebSocket = {
  isOpen: isOpen
};

function useWebSocket(url, enabledOpt) {
  var enabled = enabledOpt !== undefined ? enabledOpt : true;
  var match = React.useState(function () {
        return false;
      });
  var setIsConnected = match[1];
  var match$1 = React.useState(function () {
        return false;
      });
  var setIsDeviceConnected = match$1[1];
  var match$2 = React.useState(function () {
        return false;
      });
  var setIsPaused = match$2[1];
  var match$3 = React.useState(function () {
        
      });
  var setData = match$3[1];
  var match$4 = React.useState(function () {
        
      });
  var setError = match$4[1];
  var wsRef = React.useRef(undefined);
  var reconnectTimeoutRef = React.useRef(undefined);
  var pendingDataRef = React.useRef(undefined);
  var processingRef = React.useRef(false);
  React.useEffect((function () {
          if (enabled) {
            var connect = function () {
              try {
                var ws = new WebSocket(url);
                wsRef.current = Caml_option.some(ws);
                ws.onopen = (function () {
                    setIsConnected(function (param) {
                          return true;
                        });
                    setError(function (param) {
                          
                        });
                  });
                ws.onmessage = (function ($$event) {
                    try {
                      var parsedData = JSON.parse($$event.data);
                      var obj = Js_json.decodeObject(parsedData);
                      if (obj === undefined) {
                        return ;
                      }
                      var typeVal = Js_dict.get(obj, "type");
                      if (typeVal !== undefined) {
                        var match = Js_json.decodeString(typeVal);
                        var exit = 0;
                        if (match !== undefined) {
                          if (match === "status") {
                            var v = Js_dict.get(obj, "deviceConnected");
                            var deviceConnected;
                            if (v !== undefined) {
                              var b = Js_json.decodeBoolean(v);
                              deviceConnected = b !== undefined ? b : false;
                            } else {
                              deviceConnected = false;
                            }
                            var v$1 = Js_dict.get(obj, "paused");
                            var paused;
                            if (v$1 !== undefined) {
                              var b$1 = Js_json.decodeBoolean(v$1);
                              paused = b$1 !== undefined ? b$1 : false;
                            } else {
                              paused = false;
                            }
                            setIsDeviceConnected(function (param) {
                                  return deviceConnected;
                                });
                            return setIsPaused(function (param) {
                                        return paused;
                                      });
                          }
                          exit = 1;
                        } else {
                          exit = 1;
                        }
                        if (exit === 1) {
                          var isMockVal = Js_dict.get(obj, "is_mock");
                          if (isMockVal !== undefined) {
                            var isMock = Js_json.decodeBoolean(isMockVal);
                            if (isMock !== undefined) {
                              setIsDeviceConnected(function (param) {
                                    return !isMock;
                                  });
                            }
                            
                          }
                          pendingDataRef.current = parsedData;
                          if (!processingRef.current) {
                            processingRef.current = true;
                            globalThis.requestAnimationFrame(function () {
                                  var d = pendingDataRef.current;
                                  if (d !== undefined) {
                                    setData(function (param) {
                                          return d;
                                        });
                                    pendingDataRef.current = undefined;
                                  }
                                  processingRef.current = false;
                                });
                            return ;
                          } else {
                            return ;
                          }
                        }
                        
                      } else {
                        var isMockVal$1 = Js_dict.get(obj, "is_mock");
                        if (isMockVal$1 !== undefined) {
                          var isMock$1 = Js_json.decodeBoolean(isMockVal$1);
                          if (isMock$1 !== undefined) {
                            setIsDeviceConnected(function (param) {
                                  return !isMock$1;
                                });
                          }
                          
                        }
                        pendingDataRef.current = parsedData;
                        if (!processingRef.current) {
                          processingRef.current = true;
                          globalThis.requestAnimationFrame(function () {
                                var d = pendingDataRef.current;
                                if (d !== undefined) {
                                  setData(function (param) {
                                        return d;
                                      });
                                  pendingDataRef.current = undefined;
                                }
                                processingRef.current = false;
                              });
                          return ;
                        } else {
                          return ;
                        }
                      }
                    }
                    catch (exn){
                      console.error("Failed to parse WebSocket message");
                      return ;
                    }
                  });
                ws.onclose = (function () {
                    setIsConnected(function (param) {
                          return false;
                        });
                    var timeoutId = globalThis.setTimeout(connect, 2000);
                    reconnectTimeoutRef.current = timeoutId;
                  });
                ws.onerror = (function (err) {
                    setError(function (param) {
                          return "WebSocket error occurred";
                        });
                    console.error("WebSocket error:", err);
                  });
                return ;
              }
              catch (exn){
                setError(function (param) {
                      return "Failed to create WebSocket connection";
                    });
                console.error("WebSocket creation error");
                return ;
              }
            };
            connect();
            return (function () {
                      var timeoutId = reconnectTimeoutRef.current;
                      if (timeoutId !== undefined) {
                        globalThis.clearTimeout(timeoutId);
                      }
                      var ws = wsRef.current;
                      if (ws !== undefined) {
                        Caml_option.valFromOption(ws).close();
                        return ;
                      }
                      
                    });
          }
          var ws = wsRef.current;
          if (ws !== undefined) {
            Caml_option.valFromOption(ws).close();
            wsRef.current = undefined;
          }
          
        }), [
        url,
        enabled
      ]);
  var sendFrequencyRange = React.useCallback((function (range) {
          var ws = wsRef.current;
          if (ws === undefined) {
            return ;
          }
          var ws$1 = Caml_option.valFromOption(ws);
          if (ws$1.readyState !== 1) {
            return ;
          }
          var message = JSON.stringify(Js_dict.fromArray([
                    [
                      "type",
                      "frequency_range"
                    ],
                    [
                      "minFreq",
                      range.min
                    ],
                    [
                      "maxFreq",
                      range.max
                    ]
                  ]));
          ws$1.send(message);
        }), []);
  var sendPauseCommand = React.useCallback((function (paused) {
          var ws = wsRef.current;
          if (ws === undefined) {
            return ;
          }
          var ws$1 = Caml_option.valFromOption(ws);
          if (ws$1.readyState !== 1) {
            return ;
          }
          var message = JSON.stringify(Js_dict.fromArray([
                    [
                      "type",
                      "pause"
                    ],
                    [
                      "paused",
                      paused
                    ]
                  ]));
          ws$1.send(message);
          setIsPaused(function (param) {
                return paused;
              });
        }), []);
  return {
          isConnected: match[0],
          isDeviceConnected: match$1[0],
          isPaused: match$2[0],
          data: match$3[0],
          error: match$4[0],
          sendFrequencyRange: sendFrequencyRange,
          sendPauseCommand: sendPauseCommand
        };
}

export {
  $$WebSocket ,
  useWebSocket ,
}
/* react Not a pure module */
