// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Drei from "@react-three/drei";

function Brain(props) {
  var gltf = Drei.useGLTF("/src/glb_models/brain.glb");
  return React.createElement("primitive", {
              object: gltf.scene,
              position: [
                0.14,
                1.09,
                0.25
              ],
              scale: [
                0.45,
                0.45,
                0.45
              ]
            });
}

var make = Brain;

var $$default = Brain;

export {
  make ,
  $$default as default,
}
/* react Not a pure module */
