// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Drei from "@react-three/drei";
import * as Fiber from "@react-three/fiber";

function Brain(props) {
  var gltf = Drei.useGLTF("/src/glb_models/brain.glb");
  return Fiber.primitive(gltf.scene, [
              0.14,
              1.09,
              0.25
            ], [
              0.45,
              0.45,
              0.45
            ]);
}

var make = Brain;

var $$default = Brain;

export {
  make ,
  $$default as default,
}
/* @react-three/drei Not a pure module */
