// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Recharts from "recharts";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Float from "rescript/lib/es6/belt_Float.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as JsxRuntime from "react/jsx-runtime";

var LineChart = {};

var Line = {};

var XAxis = {};

var YAxis = {};

var CartesianGrid = {};

var Tooltip = {};

var Legend = {};

var ResponsiveContainer = {};

var Recharts$1 = {
  LineChart: LineChart,
  Line: Line,
  XAxis: XAxis,
  YAxis: YAxis,
  CartesianGrid: CartesianGrid,
  Tooltip: Tooltip,
  Legend: Legend,
  ResponsiveContainer: ResponsiveContainer
};

function calculateX(t, params) {
  var n = params.spikeCount;
  var half = (n - 1 | 0) / 2 | 0;
  var spacing = 2.0 / (n - 1 | 0);
  var halfWidth = params.spikeWidth * spacing / 2.0;
  var calculateSum = function (_k, _acc) {
    while(true) {
      var acc = _acc;
      var k = _k;
      if (k > half) {
        return acc;
      }
      var centerPos = k * spacing;
      var dx = t - centerPos;
      if (Math.abs(dx) > halfWidth) {
        _k = k + 1 | 0;
        continue ;
      }
      var local = dx / halfWidth;
      var tooth = Math.sin(Math.PI * (local + 1.0) / 2.0);
      var height;
      if (k === 0) {
        height = Math.max(1.0 * params.centerSpikeBoost, 1.05);
      } else {
        var centerHeight = Math.max(1.0 * params.centerSpikeBoost, 1.05);
        var effectiveFloor = Math.min(params.floorAmplitude, Math.min(1.0, centerHeight));
        var decay = Math.exp(- Math.abs(k) * params.decayRate);
        height = effectiveFloor + (centerHeight - effectiveFloor) * decay;
      }
      _acc = acc + height * tooth;
      _k = k + 1 | 0;
      continue ;
    };
  };
  var calculateNegativeSum = function (_k, _acc) {
    while(true) {
      var acc = _acc;
      var k = _k;
      if (k < (-half | 0)) {
        return acc;
      }
      if (k === 0) {
        _k = k - 1 | 0;
        continue ;
      }
      var centerPos = k * spacing;
      var dx = t - centerPos;
      if (Math.abs(dx) > halfWidth) {
        _k = k - 1 | 0;
        continue ;
      }
      var local = dx / halfWidth;
      var tooth = Math.sin(Math.PI * (local + 1.0) / 2.0);
      var centerHeight = Math.max(1.0 * params.centerSpikeBoost, 1.05);
      var effectiveFloor = Math.min(params.floorAmplitude, Math.min(1.0, centerHeight));
      var decay = Math.exp(- Math.abs(k) * params.decayRate);
      var height = effectiveFloor + (centerHeight - effectiveFloor) * decay;
      _acc = acc + height * tooth;
      _k = k - 1 | 0;
      continue ;
    };
  };
  var y = calculateSum(0, 0.0) + calculateNegativeSum(0, 0.0);
  var envelope = Math.exp(- Math.pow(t / params.envelopeWidth, 2.0));
  var modulation = params.baselineModulation * 0.1 * Math.sin(2.0 * Math.PI * t * 10.0);
  var envelopedY = y * envelope;
  var valleyMod = envelopedY < 0.1 ? modulation : 0.0;
  return envelopedY + valleyMod;
}

function generateData(params) {
  var points = new Array(5001);
  for(var i = 0; i <= 5000; ++i){
    var t = -1.0 + 2.0 * i / 5000;
    var freq = (t + 1.0) / 2.0 * 3.0;
    var x = calculateX(t, params);
    Belt_Array.setExn(points, i, {
          t: Belt_Option.getWithDefault(Belt_Float.fromString(t.toFixed(4)), 0.0),
          freq: Belt_Option.getWithDefault(Belt_Float.fromString(freq.toFixed(4)), 0.0),
          x: x
        });
  }
  return points;
}

function exportToSVG(params) {
  var data = generateData(params);
  var match = Belt_Array.reduce(data, [
        0.0,
        0.0
      ], (function (param, point) {
          return [
                  Math.min(param[0], point.t),
                  Math.max(param[1], point.t)
                ];
        }));
  var xMin = match[0];
  var yMax = Belt_Array.reduce(data, 0.0, (function (acc, point) {
          return Math.max(acc, point.x);
        })) * 1.1;
  var xScale = 1300 / (match[1] - xMin);
  var yScale = 300 / yMax;
  var pathData = Belt_Array.reduceWithIndex(data, "", (function (acc, point, index) {
          var x = 50 + (point.t - xMin) * xScale;
          var y = 350 - point.x * yScale;
          var cmd = index === 0 ? "M " + x.toFixed(2) + "," + y.toFixed(2) : " L " + x.toFixed(2) + "," + y.toFixed(2);
          return acc + cmd;
        }));
  var svgContent = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg width=\"" + String(1400) + "\" height=\"" + String(400) + "\" xmlns=\"http://www.w3.org/2000/svg\">\n  <rect width=\"" + String(1400) + "\" height=\"" + String(400) + "\" fill=\"#0a0a0a\"/>\n\n  <defs>\n    <pattern id=\"grid\" width=\"20\" height=\"20\" patternUnits=\"userSpaceOnUse\">\n      <path d=\"M 20 0 L 0 0 0 20\" fill=\"none\" stroke=\"#1a1a1a\" stroke-width=\"0.5\"/>\n    </pattern>\n\n    <filter id=\"glow\">\n      <feGaussianBlur stdDeviation=\"2\" result=\"coloredBlur\"/>\n      <feMerge>\n        <feMergeNode in=\"coloredBlur\"/>\n        <feMergeNode in=\"SourceGraphic\"/>\n      </feMerge>\n    </filter>\n  </defs>\n\n  <rect width=\"" + String(1400) + "\" height=\"" + String(400) + "\" fill=\"url(#grid)\"/>\n\n  <path d=\"" + pathData + "\"\n        fill=\"none\"\n        stroke=\"#00d4ff\"\n        stroke-width=\"1.5\"\n        stroke-linecap=\"round\"\n        stroke-linejoin=\"round\"\n        filter=\"url(#glow)\"/>\n\n  <line x1=\"" + String(50) + "\" y1=\"" + String(350) + "\"\n        x2=\"" + String(1350) + "\" y2=\"" + String(350) + "\"\n        stroke=\"#444\" stroke-width=\"1\"/>\n  <line x1=\"" + String(50) + "\" y1=\"" + String(50) + "\"\n        x2=\"" + String(50) + "\" y2=\"" + String(350) + "\"\n        stroke=\"#444\" stroke-width=\"1\"/>\n</svg>";
  var blobObj = new Blob([svgContent], {
        type: "image/svg+xml"
      });
  var url = URL.createObjectURL(blobObj);
  var link = document.createElement("a");
  link.href = url;
  link.download = "frequency-comb-waveform.svg";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function DrawMockNAPT(props) {
  var match = React.useState(function () {
        return 150;
      });
  var setSpikeCount = match[1];
  var spikeCount = match[0];
  var match$1 = React.useState(function () {
        return 0.5;
      });
  var setSpikeWidth = match$1[1];
  var spikeWidth = match$1[0];
  var match$2 = React.useState(function () {
        return 2.5;
      });
  var setCenterSpikeBoost = match$2[1];
  var centerSpikeBoost = match$2[0];
  var match$3 = React.useState(function () {
        return 1.0;
      });
  var setFloorAmplitude = match$3[1];
  var floorAmplitude = match$3[0];
  var match$4 = React.useState(function () {
        return 0.5;
      });
  var setDecayRate = match$4[1];
  var decayRate = match$4[0];
  var match$5 = React.useState(function () {
        return 0.0;
      });
  var setBaselineModulation = match$5[1];
  var baselineModulation = match$5[0];
  var match$6 = React.useState(function () {
        return 10.0;
      });
  var setEnvelopeWidth = match$6[1];
  var envelopeWidth = match$6[0];
  var params = {
    spikeCount: spikeCount,
    spikeWidth: spikeWidth,
    centerSpikeBoost: centerSpikeBoost,
    floorAmplitude: floorAmplitude,
    decayRate: decayRate,
    baselineModulation: baselineModulation,
    envelopeWidth: envelopeWidth
  };
  var data = React.useMemo((function () {
          return generateData(params);
        }), [params]);
  var handleExport = React.useCallback((function () {
          exportToSVG(params);
        }), [params]);
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("h2", {
                            children: "APT Frequency Comb",
                            className: "text-2xl font-bold mb-4 text-center dark:text-white"
                          }),
                      JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx(Recharts.ResponsiveContainer, {
                                  width: "100%",
                                  height: 400,
                                  children: JsxRuntime.jsxs(Recharts.LineChart, {
                                        data: data,
                                        children: [
                                          JsxRuntime.jsx(Recharts.CartesianGrid, {
                                                strokeDasharray: "3 3"
                                              }),
                                          JsxRuntime.jsx(Recharts.XAxis, {
                                                dataKey: "freq",
                                                label: {
                                                  value: "Frequency (MHz)",
                                                  position: "insideBottom",
                                                  offset: -5
                                                }
                                              }),
                                          JsxRuntime.jsx(Recharts.YAxis, {
                                                label: {
                                                  value: "x(t)",
                                                  angle: -90,
                                                  position: "insideLeft"
                                                }
                                              }),
                                          JsxRuntime.jsx(Recharts.Tooltip, {}),
                                          JsxRuntime.jsx(Recharts.Legend, {}),
                                          JsxRuntime.jsx(Recharts.Line, {
                                                type_: "monotone",
                                                dataKey: "x",
                                                stroke: "#2563eb",
                                                strokeWidth: 2,
                                                dot: false,
                                                name: "x(t)"
                                              })
                                        ]
                                      })
                                }),
                            className: "mb-6"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("label", {
                                            children: "Spike Count: " + String(spikeCount),
                                            className: "block text-sm font-medium mb-2 dark:text-gray-300"
                                          }),
                                      JsxRuntime.jsx("input", {
                                            className: "w-full",
                                            max: "200",
                                            min: "3",
                                            step: 1.0,
                                            type: "range",
                                            value: String(spikeCount),
                                            onChange: (function (e) {
                                                var value = e.target.value;
                                                setSpikeCount(function (param) {
                                                      return Belt_Option.getWithDefault(Belt_Int.fromString(value), 150);
                                                    });
                                              })
                                          })
                                    ]
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("label", {
                                            children: "Spike Width Ratio: " + spikeWidth.toFixed(2),
                                            className: "block text-sm font-medium mb-2 dark:text-gray-300"
                                          }),
                                      JsxRuntime.jsx("input", {
                                            className: "w-full",
                                            max: "1.0",
                                            min: "0.01",
                                            step: 0.01,
                                            type: "range",
                                            value: spikeWidth.toString(),
                                            onChange: (function (e) {
                                                var value = e.target.value;
                                                setSpikeWidth(function (param) {
                                                      return Belt_Option.getWithDefault(Belt_Float.fromString(value), 0.5);
                                                    });
                                              })
                                          })
                                    ]
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("label", {
                                            children: "Center Spike Boost: " + centerSpikeBoost.toFixed(2) + "x",
                                            className: "block text-sm font-medium mb-2 dark:text-gray-300"
                                          }),
                                      JsxRuntime.jsx("input", {
                                            className: "w-full",
                                            max: "5.0",
                                            min: "1.05",
                                            step: 0.01,
                                            type: "range",
                                            value: centerSpikeBoost.toString(),
                                            onChange: (function (e) {
                                                var value = e.target.value;
                                                setCenterSpikeBoost(function (param) {
                                                      return Belt_Option.getWithDefault(Belt_Float.fromString(value), 2.5);
                                                    });
                                              })
                                          })
                                    ]
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("label", {
                                            children: "Floor Amplitude: " + floorAmplitude.toFixed(2),
                                            className: "block text-sm font-medium mb-2 dark:text-gray-300"
                                          }),
                                      JsxRuntime.jsx("input", {
                                            className: "w-full",
                                            max: "1.0",
                                            min: "0.1",
                                            step: 0.01,
                                            type: "range",
                                            value: floorAmplitude.toString(),
                                            onChange: (function (e) {
                                                var value = e.target.value;
                                                setFloorAmplitude(function (param) {
                                                      return Belt_Option.getWithDefault(Belt_Float.fromString(value), 1.0);
                                                    });
                                              })
                                          })
                                    ]
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("label", {
                                            children: "Decay Rate: " + decayRate.toFixed(2),
                                            className: "block text-sm font-medium mb-2 dark:text-gray-300"
                                          }),
                                      JsxRuntime.jsx("input", {
                                            className: "w-full",
                                            max: "5.0",
                                            min: "0.1",
                                            step: 0.1,
                                            type: "range",
                                            value: decayRate.toString(),
                                            onChange: (function (e) {
                                                var value = e.target.value;
                                                setDecayRate(function (param) {
                                                      return Belt_Option.getWithDefault(Belt_Float.fromString(value), 0.5);
                                                    });
                                              })
                                          })
                                    ]
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("label", {
                                            children: "Baseline Modulation: " + baselineModulation.toFixed(2),
                                            className: "block text-sm font-medium mb-2 dark:text-gray-300"
                                          }),
                                      JsxRuntime.jsx("input", {
                                            className: "w-full",
                                            max: "1.0",
                                            min: "0.0",
                                            step: 0.01,
                                            type: "range",
                                            value: baselineModulation.toString(),
                                            onChange: (function (e) {
                                                var value = e.target.value;
                                                setBaselineModulation(function (param) {
                                                      return Belt_Option.getWithDefault(Belt_Float.fromString(value), 0.0);
                                                    });
                                              })
                                          })
                                    ]
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("label", {
                                            children: "Envelope Width: " + envelopeWidth.toFixed(2),
                                            className: "block text-sm font-medium mb-2 dark:text-gray-300"
                                          }),
                                      JsxRuntime.jsx("input", {
                                            className: "w-full",
                                            max: "2.0",
                                            min: "0.1",
                                            step: 0.01,
                                            type: "range",
                                            value: envelopeWidth.toString(),
                                            onChange: (function (e) {
                                                var value = e.target.value;
                                                setEnvelopeWidth(function (param) {
                                                      return Belt_Option.getWithDefault(Belt_Float.fromString(value), 10.0);
                                                    });
                                              })
                                          })
                                    ]
                                  })
                            ],
                            className: "grid grid-cols-2 md:grid-cols-4 gap-4 mb-4"
                          }),
                      JsxRuntime.jsx("button", {
                            children: "Export as SVG",
                            className: "mt-4 px-4 py-2 bg-blue-600 dark:bg-blue-500 text-white rounded hover:bg-blue-700 dark:hover:bg-blue-600",
                            onClick: (function (param) {
                                handleExport();
                              })
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("h3", {
                                    children: "About:",
                                    className: "font-semibold mb-2 dark:text-white"
                                  }),
                              JsxRuntime.jsx("p", {
                                    children: "APT (Automatic Picture Transmission) frequency comb with " + String(spikeCount) + " spikes. Sine wave profiles with exponential height decay from center to floor, modulated by Gaussian envelope.",
                                    className: "text-sm text-gray-700 dark:text-gray-300"
                                  })
                            ],
                            className: "mt-6 p-4 bg-blue-50 dark:bg-blue-900 rounded"
                          })
                    ],
                    className: "max-w-6xl mx-auto bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6"
                  }),
              className: "w-full h-full p-6 bg-gray-50 dark:bg-gray-900"
            });
}

var make = DrawMockNAPT;

var $$default = DrawMockNAPT;

export {
  Recharts$1 as Recharts,
  calculateX ,
  generateData ,
  exportToSVG ,
  make ,
  $$default as default,
}
/* react Not a pure module */
