// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function formatFreq(freq) {
  if (freq < 1.0) {
    return (freq * 1000.0).toFixed(0) + "kHz";
  } else {
    return freq.toFixed(1) + "MHz";
  }
}

function FrequencyRangeSlider(props) {
  var onRangeChange = props.onRangeChange;
  var __onActivate = props.onActivate;
  var __isActive = props.isActive;
  var __stepSize = props.stepSize;
  var __label = props.label;
  var __visibleMax = props.visibleMax;
  var __visibleMin = props.visibleMin;
  var __maxFreq = props.maxFreq;
  var __minFreq = props.minFreq;
  var minFreq = __minFreq !== undefined ? __minFreq : 0.0;
  var maxFreq = __maxFreq !== undefined ? __maxFreq : 4.75;
  var visibleMin = __visibleMin !== undefined ? __visibleMin : 0.0;
  var visibleMax = __visibleMax !== undefined ? __visibleMax : 3.2;
  var label = __label !== undefined ? __label : "A";
  var stepSize = __stepSize !== undefined ? __stepSize : 0.033;
  var isActive = __isActive !== undefined ? __isActive : false;
  var onActivate = __onActivate !== undefined ? __onActivate : (function () {
        
      });
  var totalRange = maxFreq - minFreq;
  var windowWidth = (visibleMax - visibleMin) / totalRange;
  var match = React.useState(function () {
        return (visibleMin - minFreq) / totalRange;
      });
  var setWindowStart = match[1];
  var windowStart = match[0];
  var match$1 = React.useState(function () {
        return false;
      });
  var setIsDragging = match$1[1];
  var isDragging = match$1[0];
  var isDraggingRef = React.useRef(false);
  var trackRef = React.useRef(undefined);
  var containerRef = React.useRef(undefined);
  var dragStartXRef = React.useRef(0.0);
  var dragStartWindowRef = React.useRef(0.0);
  var currentMin = minFreq + windowStart * totalRange;
  var currentMax = minFreq + (windowStart + windowWidth) * totalRange;
  var notifyParent = React.useCallback((function () {
          if (isActive && onRangeChange !== undefined) {
            return onRangeChange({
                        min: currentMin,
                        max: currentMax
                      });
          }
          
        }), [
        isActive,
        onRangeChange,
        currentMin,
        currentMax
      ]);
  React.useEffect((function () {
          if (isActive && isDragging && onRangeChange !== undefined) {
            onRangeChange({
                  min: currentMin,
                  max: currentMax
                });
          }
          
        }), [
        windowStart,
        isActive,
        onRangeChange,
        currentMin,
        currentMax,
        isDragging
      ]);
  React.useEffect((function () {
          if (isActive && !isDragging && onRangeChange !== undefined) {
            onRangeChange({
                  min: currentMin,
                  max: currentMax
                });
          }
          
        }), [
        windowStart,
        isActive,
        onRangeChange,
        currentMin,
        currentMax,
        isDragging
      ]);
  var moveWindow = React.useCallback((function (direction) {
          var stepPercent = stepSize / totalRange;
          setWindowStart(function (prev) {
                var delta = direction === "up" ? stepPercent : - stepPercent;
                var newStart = prev + delta;
                return Math.max(0.0, Math.min(1.0 - windowWidth, newStart));
              });
        }), [
        stepSize,
        totalRange,
        windowWidth
      ]);
  React.useEffect((function () {
          var handleKeyDown = function (e) {
            if (!isActive) {
              return ;
            }
            var match = e.key;
            switch (match) {
              case "ArrowDown" :
                  e.preventDefault();
                  return moveWindow("down");
              case "ArrowUp" :
                  e.preventDefault();
                  return moveWindow("up");
              default:
                return ;
            }
          };
          window.addEventListener("keydown", handleKeyDown);
          return (function () {
                    window.removeEventListener("keydown", handleKeyDown);
                  });
        }), [
        isActive,
        moveWindow
      ]);
  React.useEffect((function () {
          var handleMouseMove = function (e) {
            if (!isDraggingRef.current) {
              return ;
            }
            var track = trackRef.current;
            if (track === undefined) {
              return ;
            }
            var rect = Caml_option.valFromOption(track).getBoundingClientRect();
            var deltaX = e.clientX - dragStartXRef.current;
            var deltaPercent = deltaX / rect.width;
            var newStart = dragStartWindowRef.current + deltaPercent;
            var clampedStart = Math.max(0.0, Math.min(1.0 - windowWidth, newStart));
            setWindowStart(function (param) {
                  return clampedStart;
                });
          };
          var handleMouseUp = function (_e) {
            if (isDraggingRef.current) {
              isDraggingRef.current = false;
              setIsDragging(function (param) {
                    return false;
                  });
              return notifyParent();
            }
            
          };
          window.addEventListener("mousemove", handleMouseMove);
          window.addEventListener("mouseup", handleMouseUp);
          return (function () {
                    window.removeEventListener("mousemove", handleMouseMove);
                    window.removeEventListener("mouseup", handleMouseUp);
                  });
        }), [
        windowWidth,
        notifyParent,
        setWindowStart
      ]);
  var handleMouseDown = React.useCallback((function (e) {
          e.stopPropagation();
          isDraggingRef.current = true;
          setIsDragging(function (param) {
                return true;
              });
          dragStartXRef.current = e.clientX;
          dragStartWindowRef.current = windowStart;
        }), [windowStart]);
  var handleContainerClick = React.useCallback((function (e) {
          var target = e.target;
          var container = containerRef.current;
          var shouldActivate = container !== undefined && Caml_option.valFromOption(container) === target ? true : target.closest(".range-track") !== undefined;
          if (shouldActivate) {
            return onActivate();
          }
          
        }), [onActivate]);
  var sliderWrapperStyle = {
    display: "flex",
    marginBottom: "16px",
    alignItems: "center",
    userSelect: "none"
  };
  var labelContainerStyle = {
    display: "flex",
    width: "32px",
    alignItems: "center",
    flexShrink: "0",
    justifyContent: "center"
  };
  var labelStyle = {
    color: isActive ? "#00d4ff" : "#666",
    fontSize: "24px",
    fontWeight: "700",
    transition: "color 0.2s ease"
  };
  var sliderContainerStyle = {
    backgroundColor: isActive ? "rgba(0, 212, 255, 0.05)" : "transparent",
    border: "1px solid " + (
      isActive ? "#00d4ff" : "transparent"
    ),
    cursor: "pointer",
    outline: "none",
    padding: "8px",
    borderRadius: "6px",
    flex: "1",
    transition: "border-color 0.2s ease, background-color 0.2s ease",
    userSelect: "none"
  };
  var rangeTrackStyle = {
    backgroundColor: "#0f0f0f",
    border: "1px solid #1a1a1a",
    height: "32px",
    overflow: "hidden",
    position: "relative",
    borderRadius: "4px",
    userSelect: "none"
  };
  var rangeLabelsStyle = {
    bottom: "0",
    color: "#444",
    display: "flex",
    fontSize: "9px",
    left: "0",
    padding: "0 12px",
    position: "absolute",
    right: "0",
    top: "0",
    alignItems: "center",
    justifyContent: "space-between",
    userSelect: "none",
    pointerEvents: "none"
  };
  var visibleWindowStyle = {
    backgroundColor: isActive ? "rgba(0, 212, 255, 0.15)" : "rgba(128, 128, 128, 0.15)",
    border: "1px solid " + (
      isActive ? "#00d4ff" : "#808080"
    ),
    bottom: "2px",
    cursor: "grab",
    display: "flex",
    left: (windowStart * 100.0).toString() + "%",
    minWidth: "80px",
    padding: "0 6px",
    position: "absolute",
    top: "2px",
    width: (windowWidth * 100.0).toString() + "%",
    borderRadius: "2px",
    alignItems: "center",
    justifyContent: "center",
    boxSizing: "border-box",
    userSelect: "none"
  };
  var windowLabelStyle = {
    color: isActive ? "#00d4ff" : "#808080",
    fontSize: "9px",
    whiteSpace: "nowrap",
    userSelect: "none",
    pointerEvents: "none"
  };
  var rangeInfoStyle = {
    display: "flex",
    fontSize: "11px",
    marginTop: "8px",
    padding: "0 4px",
    alignItems: "center",
    justifyContent: "space-between",
    userSelect: "none"
  };
  var rangeLabelStyle = {
    color: isActive ? "#00d4ff" : "#666",
    fontWeight: isActive ? "500" : "400",
    userSelect: "none"
  };
  var rangeValueStyle = {
    color: isActive ? "#00d4ff" : "#808080",
    fontWeight: "500",
    userSelect: "none"
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("div", {
                            children: label,
                            style: labelStyle
                          }),
                      style: labelContainerStyle
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("span", {
                                              children: formatFreq(minFreq)
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: formatFreq(maxFreq)
                                            })
                                      ],
                                      style: rangeLabelsStyle
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsx("div", {
                                            children: formatFreq(currentMin) + " - " + formatFreq(currentMax),
                                            style: windowLabelStyle
                                          }),
                                      style: visibleWindowStyle,
                                      onMouseDown: handleMouseDown
                                    })
                              ],
                              ref: Caml_option.some(function (el) {
                                    trackRef.current = (el == null) ? undefined : Caml_option.some(el);
                                  }),
                              className: "range-track",
                              style: rangeTrackStyle
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: formatFreq(minFreq) + " to " + formatFreq(maxFreq),
                                      style: rangeLabelStyle
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: formatFreq(currentMin) + " to " + formatFreq(currentMax),
                                      style: rangeValueStyle
                                    })
                              ],
                              style: rangeInfoStyle
                            })
                      ],
                      ref: Caml_option.some(function (el) {
                            containerRef.current = (el == null) ? undefined : Caml_option.some(el);
                          }),
                      style: sliderContainerStyle,
                      tabIndex: 0,
                      onClick: handleContainerClick
                    })
              ],
              style: sliderWrapperStyle
            });
}

var make = FrequencyRangeSlider;

export {
  formatFreq ,
  make ,
}
/* react Not a pure module */
