// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Gsap from "gsap";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as BrainResMjs from "./Brain.res.mjs";
import * as Drei from "@react-three/drei";
import * as JsxRuntime from "react/jsx-runtime";
import * as Fiber from "@react-three/fiber";

var Canvas = {};

var OrbitControls = {};

var TransformControls = {};

var Three = {};

var Gsap$1 = {};

var areas = [
  {
    name: "Head",
    position: [
      0.0,
      1.0,
      0.2
    ],
    target: [
      0.0,
      1.0,
      0.0
    ],
    meshName: "head"
  },
  {
    name: "Throat",
    position: [
      0.0,
      1.2,
      0.2
    ],
    target: [
      0.0,
      1.2,
      0.0
    ],
    meshName: "throat"
  },
  {
    name: "Mouth",
    position: [
      0.0,
      1.4,
      0.2
    ],
    target: [
      0.0,
      1.4,
      0.0
    ],
    meshName: "mouth"
  },
  {
    name: "Torso",
    position: [
      0.0,
      0.0,
      0.2
    ],
    target: [
      0.0,
      0.0,
      0.0
    ],
    meshName: "torso"
  },
  {
    name: "Heart",
    position: [
      0.0,
      0.5,
      0.2
    ],
    target: [
      0.0,
      0.5,
      0.0
    ],
    meshName: "heart"
  },
  {
    name: "Left Arm",
    position: [
      -0.5,
      0.0,
      0.2
    ],
    target: [
      -0.5,
      0.0,
      0.0
    ],
    meshName: "left_arm"
  },
  {
    name: "Right Arm",
    position: [
      0.5,
      0.0,
      0.2
    ],
    target: [
      0.5,
      0.0,
      0.0
    ],
    meshName: "right_arm"
  },
  {
    name: "Left Leg",
    position: [
      -0.3,
      -1.0,
      0.2
    ],
    target: [
      -0.3,
      -1.0,
      0.0
    ],
    meshName: "left_leg"
  },
  {
    name: "Right Leg",
    position: [
      0.3,
      -1.0,
      0.2
    ],
    target: [
      0.3,
      -1.0,
      0.0
    ],
    meshName: "right_leg"
  }
];

var make = BrainResMjs.make;

var Brain = {
  make: make
};

function HumanModelViewer$Model(props) {
  var gltf = Drei.useGLTF("/src/glb_models/androgynous_body.glb");
  React.useEffect((function () {
          
        }), [
        gltf.scene,
        props.selectedArea
      ]);
  return React.createElement("primitive", {
              object: gltf.scene
            });
}

var Model = {
  make: HumanModelViewer$Model
};

function ambient() {
  return React.createElement("ambientLight", {
              intensity: 0.5
            });
}

function directional() {
  return React.createElement("directionalLight", {
              position: [
                10.0,
                10.0,
                5.0
              ],
              intensity: 1.0
            });
}

var Lights = {
  ambient: ambient,
  directional: directional
};

function HumanModelViewer(props) {
  var __height = props.height;
  var __width = props.width;
  var width = __width !== undefined ? __width : "100%";
  var height = __height !== undefined ? __height : "100%";
  var match = React.useState(function () {
        
      });
  var setSelectedArea = match[1];
  var selectedArea = match[0];
  var controlsRef = React.useRef(null);
  React.useEffect((function () {
          var match = controlsRef.current;
          if (selectedArea !== undefined && !(match == null)) {
            var match$1 = selectedArea.position;
            var match$2 = selectedArea.target;
            Gsap.to(match.object.position, {
                  x: match$1[0],
                  y: match$1[1],
                  z: match$1[2],
                  duration: 1.0
                });
            Gsap.to(match.target, {
                  x: match$2[0],
                  y: match$2[1],
                  z: match$2[2],
                  duration: 1.0,
                  onUpdate: (function () {
                      match.update();
                    })
                });
          }
          
        }), [selectedArea]);
  var containerStyle = {
    height: height,
    position: "relative",
    width: width
  };
  var sidebarStyle = {
    background: "rgba(0,0,0,0.8)",
    color: "white",
    height: "100%",
    left: "0",
    padding: "10px",
    position: "absolute",
    top: "0",
    width: "200px",
    zIndex: "1"
  };
  var buttonStyle = {
    backgroundColor: "#333",
    border: "1px solid #555",
    color: "white",
    cursor: "pointer",
    display: "block",
    margin: "5px 0",
    padding: "8px",
    width: "100%",
    borderRadius: "4px"
  };
  var canvasStyle = {
    height: "100%",
    left: "200px",
    position: "absolute",
    width: "calc(100% - 200px)"
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h3", {
                              children: "Body Areas"
                            }),
                        Belt_Array.map(areas, (function (area) {
                                return JsxRuntime.jsx("button", {
                                            children: area.name,
                                            style: buttonStyle,
                                            onClick: (function (param) {
                                                setSelectedArea(function (param) {
                                                      return area;
                                                    });
                                              })
                                          }, area.name);
                              }))
                      ],
                      style: sidebarStyle
                    }),
                JsxRuntime.jsx(Fiber.Canvas, {
                      style: canvasStyle,
                      camera: {
                        position: [
                          0.0,
                          0.0,
                          5.0
                        ],
                        fov: 75
                      },
                      children: JsxRuntime.jsxs(React.Suspense, {
                            children: [
                              ambient(),
                              directional(),
                              JsxRuntime.jsx(Drei.TransformControls, {
                                    mode: "translate",
                                    children: JsxRuntime.jsx(HumanModelViewer$Model, {
                                          selectedArea: selectedArea
                                        })
                                  }),
                              JsxRuntime.jsx(make, {}),
                              JsxRuntime.jsx(Drei.OrbitControls, {
                                    ref: Caml_option.some(controlsRef)
                                  })
                            ],
                            fallback: Caml_option.some(null)
                          })
                    })
              ],
              style: containerStyle
            });
}

var make$1 = HumanModelViewer;

var $$default = HumanModelViewer;

export {
  Canvas ,
  OrbitControls ,
  TransformControls ,
  Three ,
  Gsap$1 as Gsap,
  areas ,
  Brain ,
  Model ,
  Lights ,
  make$1 as make,
  $$default as default,
}
/* make Not a pure module */
