// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function InfoPopover(props) {
  var __title = props.title;
  var title = __title !== undefined ? __title : "Information";
  var match = React.useState(function () {
        return false;
      });
  var setIsVisible = match[1];
  var isVisible = match[0];
  var match$1 = React.useState(function () {
        return {
                x: 0.0,
                y: 0.0
              };
      });
  var setPosition = match$1[1];
  var position = match$1[0];
  var iconRef = React.useRef(null);
  var handleMouseEnter = function () {
    var el = iconRef.current;
    if (!(el == null)) {
      var rect = el.getBoundingClientRect();
      setPosition(function (param) {
            return {
                    x: rect.right + 12.0,
                    y: rect.top + rect.height / 2.0
                  };
          });
    }
    setIsVisible(function (param) {
          return true;
        });
  };
  var containerStyle = {
    display: "inline-flex",
    position: "relative",
    alignItems: "center"
  };
  var iconStyle = {
    backgroundColor: "#2a2a2a",
    border: "1px solid #3a3a3a",
    color: "#666",
    cursor: "help",
    display: "flex",
    fontSize: "10px",
    fontWeight: "600",
    height: "16px",
    marginLeft: "8px",
    width: "16px",
    borderRadius: "50%",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s ease"
  };
  var popoverStyle = {
    backgroundColor: "#1a1a1a",
    border: "1px solid #2a2a2a",
    left: position.x.toString() + "px",
    padding: "16px",
    position: "fixed",
    top: position.y.toString() + "px",
    visibility: isVisible ? "visible" : "hidden",
    width: "280px",
    zIndex: "9999",
    opacity: isVisible ? "1" : "0",
    borderRadius: "8px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.5)",
    transition: "opacity 0.2s ease, visibility 0.2s ease",
    transform: "translateY(-50%)",
    pointerEvents: "none"
  };
  var titleStyle = {
    color: "#ccc",
    fontSize: "12px",
    fontWeight: "600",
    marginBottom: "8px"
  };
  var textStyle = {
    color: "#888",
    fontSize: "11px",
    lineHeight: "1.5"
  };
  var arrowBeforeStyle = {
    borderTop: "6px solid transparent",
    borderRight: "6px solid #2a2a2a",
    borderBottom: "6px solid transparent",
    height: "0",
    left: "-6px",
    position: "absolute",
    top: "50%",
    width: "0",
    transform: "translateY(-50%)"
  };
  var arrowAfterStyle = {
    borderTop: "5px solid transparent",
    borderRight: "5px solid #1a1a1a",
    borderBottom: "5px solid transparent",
    height: "0",
    left: "-5px",
    position: "absolute",
    top: "50%",
    width: "0",
    transform: "translateY(-50%)"
  };
  var popoverContent = JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
                style: arrowBeforeStyle
              }),
          JsxRuntime.jsx("div", {
                style: arrowAfterStyle
              }),
          JsxRuntime.jsx("div", {
                children: title,
                style: titleStyle
              }),
          JsxRuntime.jsx("div", {
                children: props.content,
                style: textStyle
              })
        ],
        style: popoverStyle
      });
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: "i",
                      ref: Caml_option.some(iconRef),
                      className: "info-icon",
                      style: iconStyle
                    }),
                ReactDom.createPortal(popoverContent, document.body)
              ],
              style: containerStyle,
              onMouseEnter: (function (param) {
                  handleMouseEnter();
                }),
              onMouseLeave: (function (param) {
                  setIsVisible(function (param) {
                        return false;
                      });
                })
            });
}

var make = InfoPopover;

export {
  make ,
}
/* react Not a pure module */
