// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Js_array from "rescript/lib/es6/js_array.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as InfoPopoverResMjs from "./InfoPopover.res.mjs";
import * as FrequencyRangeSliderResMjs from "./FrequencyRangeSlider.res.mjs";

var make = FrequencyRangeSliderResMjs.make;

var FrequencyRangeSlider = {
  make: make
};

var make$1 = InfoPopoverResMjs.make;

var InfoPopover = {
  make: make$1
};

function Sidebar(props) {
  var onClear = props.onClear;
  var onStitch = props.onStitch;
  var onSelectedFilesChange = props.onSelectedFilesChange;
  var selectedFiles = props.selectedFiles;
  var onPauseToggle = props.onPauseToggle;
  var onFrequencyRangeChange = props.onFrequencyRangeChange;
  var onSignalAreaChange = props.onSignalAreaChange;
  var activeSignalArea = props.activeSignalArea;
  var onTabChange = props.onTabChange;
  var activeTab = props.activeTab;
  var isPaused = props.isPaused;
  var isDeviceConnected = props.isDeviceConnected;
  var isConnected = props.isConnected;
  var match = React.useState(function () {
        return 103432;
      });
  var setFftSize = match[1];
  var match$1 = React.useState(function () {
        return "Rectangular";
      });
  var setFftWindow = match$1[1];
  var match$2 = React.useState(function () {
        return 60;
      });
  var setFftFrameRate = match$2[1];
  var lastNotifiedRangeRef = React.useRef({
        min: 0.0,
        max: 3.2
      });
  var handleAreaARangeChange = React.useCallback((function (range) {
          if (activeSignalArea !== "A") {
            return ;
          }
          var minDiff = Math.abs(range.min - lastNotifiedRangeRef.current.min);
          var maxDiff = Math.abs(range.max - lastNotifiedRangeRef.current.max);
          if (minDiff > 0.01 || maxDiff > 0.01) {
            lastNotifiedRangeRef.current = range;
            return onFrequencyRangeChange(range);
          }
          
        }), [activeSignalArea]);
  var handleAreaBRangeChange = React.useCallback((function (range) {
          if (activeSignalArea !== "B") {
            return ;
          }
          var minDiff = Math.abs(range.min - lastNotifiedRangeRef.current.min);
          var maxDiff = Math.abs(range.max - lastNotifiedRangeRef.current.max);
          if (minDiff > 0.01 || maxDiff > 0.01) {
            lastNotifiedRangeRef.current = range;
            return onFrequencyRangeChange(range);
          }
          
        }), [activeSignalArea]);
  var handleFileInputChange = function ($$event) {
    var target = $$event.target;
    var files = target.files;
    if (files == null) {
      return ;
    }
    var fileArray = Array.from(files);
    onSelectedFilesChange(fileArray);
  };
  var handleBrowseClick = function () {
    var el = document.getElementById("fileInput");
    if (el !== undefined) {
      Caml_option.valFromOption(el).click();
      return ;
    }
    
  };
  var handleStitch = function () {
    console.log("Sidebar stitch button clicked");
    onStitch();
  };
  var handleClear = function () {
    console.log("Sidebar clear button clicked");
    onClear();
  };
  var sidebarContainerStyle = {
    backgroundColor: "#0d0d0d",
    borderRight: "1px solid #1a1a1a",
    display: "flex",
    height: "100vh",
    minWidth: "360px",
    overflowX: "visible",
    overflowY: "auto",
    padding: "24px",
    position: "relative",
    width: "360px",
    flexDirection: "column"
  };
  var connectionStatusContainerStyle = {
    display: "flex",
    marginBottom: "24px",
    alignItems: "center",
    gridColumnGap: "8px",
    gridRowGap: "8px"
  };
  var connectionStatusStyle = {
    backgroundColor: "#141414",
    border: "1px solid #1f1f1f",
    display: "flex",
    padding: "12px 16px",
    borderRadius: "8px",
    alignItems: "center",
    flex: "0 0 70%",
    gridColumnGap: "8px",
    gridRowGap: "8px"
  };
  var getStatusDotStyle = function (connected) {
    return {
            backgroundColor: connected ? "#00d4ff" : "#ff4444",
            height: "8px",
            width: "8px",
            borderRadius: "50%",
            boxShadow: connected ? "0 0 8px #00d4ff" : "0 0 8px #ff4444",
            flexShrink: "0"
          };
  };
  var statusTextStyle = {
    color: "#888",
    fontSize: "12px",
    fontWeight: "500"
  };
  var getPauseButtonStyle = function (paused) {
    return {
            backgroundColor: paused ? "#2a2a2a" : "#1a1a1a",
            border: "1px solid " + (
              paused ? "#00d4ff" : "#2a2a2a"
            ),
            color: paused ? "#00d4ff" : "#ccc",
            cursor: "pointer",
            fontFamily: "'JetBrains Mono', monospace",
            fontSize: "12px",
            fontWeight: "500",
            padding: "12px 8px",
            textAlign: "center",
            borderRadius: "8px",
            flex: "0 0 25%",
            transition: "all 0.2s ease",
            userSelect: "none"
          };
  };
  var tabContainerStyle = {
    display: "flex",
    marginBottom: "24px",
    flexDirection: "column",
    gridColumnGap: "8px",
    gridRowGap: "8px"
  };
  var getTabStyle = function (isActive) {
    return {
            backgroundColor: isActive ? "#1a1a1a" : "transparent",
            border: "1px solid " + (
              isActive ? "#2a2a2a" : "transparent"
            ),
            color: isActive ? "#00d4ff" : "#666",
            cursor: "pointer",
            fontFamily: "'JetBrains Mono', monospace",
            fontSize: "13px",
            fontWeight: "500",
            padding: "12px 16px",
            textAlign: "left",
            borderRadius: "8px",
            transition: "all 0.2s ease",
            userSelect: "none"
          };
  };
  var sectionStyle = {
    marginBottom: "24px"
  };
  var sectionTitleStyle = {
    color: "#555",
    display: "flex",
    fontSize: "11px",
    letterSpacing: "1px",
    marginBottom: "12px",
    textTransform: "uppercase",
    alignItems: "center",
    gridColumnGap: "8px",
    gridRowGap: "8px"
  };
  var settingRowStyle = {
    backgroundColor: "#141414",
    border: "1px solid #1a1a1a",
    display: "flex",
    marginBottom: "8px",
    padding: "10px 12px",
    borderRadius: "6px",
    alignItems: "center",
    justifyContent: "space-between",
    userSelect: "none"
  };
  var settingLabelContainerStyle = {
    display: "flex",
    alignItems: "center"
  };
  var settingLabelStyle = {
    color: "#777",
    fontSize: "12px"
  };
  var settingValueStyle = {
    color: "#ccc",
    fontSize: "12px",
    fontWeight: "500"
  };
  var settingSelectStyle = {
    backgroundColor: "transparent",
    border: "1px solid transparent",
    color: "#ccc",
    cursor: "pointer",
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: "12px",
    fontWeight: "500",
    minWidth: "80px",
    padding: "2px 6px",
    borderRadius: "4px"
  };
  var settingInputStyle = {
    backgroundColor: "transparent",
    border: "1px solid transparent",
    color: "#ccc",
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: "12px",
    fontWeight: "500",
    padding: "2px 6px",
    textAlign: "center",
    width: "50px",
    borderRadius: "4px"
  };
  var flexGapStyle = {
    display: "flex",
    alignItems: "center",
    gridColumnGap: "4px",
    gridRowGap: "4px"
  };
  var fpsTextStyle = {
    color: "#ccc",
    fontSize: "12px",
    fontWeight: "500"
  };
  var browseButtonStyle = {
    backgroundColor: "#1a1a1a",
    border: "1px solid #2a2a2a",
    color: "#ccc",
    cursor: "pointer",
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: "11px",
    fontWeight: "500",
    padding: "8px 12px",
    borderRadius: "8px",
    flex: "none"
  };
  var fileNameStyle = {
    fontSize: "11px",
    maxWidth: "240px",
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis"
  };
  var removeButtonStyle = {
    background: "transparent",
    border: "1px solid #2a2a2a",
    color: "#ccc",
    cursor: "pointer",
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: "10px",
    fontWeight: "500",
    padding: "4px 8px",
    borderRadius: "8px",
    flex: "none"
  };
  var buttonRowStyle = {
    display: "flex",
    gridColumnGap: "8px",
    gridRowGap: "8px"
  };
  var flexButtonStyle = {
    backgroundColor: "#1a1a1a",
    border: "1px solid #2a2a2a",
    color: "#ccc",
    cursor: "pointer",
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: "12px",
    fontWeight: "500",
    padding: "12px 8px",
    textAlign: "center",
    borderRadius: "8px",
    flex: "1"
  };
  var transparentButtonStyle = {
    background: "transparent",
    border: "1px solid #2a2a2a",
    color: "#ccc",
    cursor: "pointer",
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: "12px",
    fontWeight: "500",
    padding: "12px 8px",
    textAlign: "center",
    borderRadius: "8px",
    flex: "1"
  };
  var tmp;
  switch (activeTab) {
    case "stitcher" :
        tmp = JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "File selection",
                              style: sectionTitleStyle
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsx("span", {
                                            children: "Choose files...",
                                            style: settingLabelStyle
                                          }),
                                      style: settingLabelContainerStyle
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("input", {
                                              id: "fileInput",
                                              style: {
                                                display: "none"
                                              },
                                              accept: ".c64",
                                              multiple: true,
                                              type: "file",
                                              onChange: handleFileInputChange
                                            }),
                                        JsxRuntime.jsx("button", {
                                              children: "Browse",
                                              style: browseButtonStyle,
                                              onClick: (function (param) {
                                                  handleBrowseClick();
                                                })
                                            })
                                      ],
                                      style: flexGapStyle
                                    })
                              ],
                              style: settingRowStyle
                            })
                      ],
                      style: sectionStyle
                    }),
                selectedFiles.length > 0 ? JsxRuntime.jsxs(JsxRuntime.Fragment, {
                        children: [
                          JsxRuntime.jsxs("div", {
                                children: [
                                  JsxRuntime.jsx("div", {
                                        children: "Selected files (" + String(selectedFiles.length) + ")",
                                        style: sectionTitleStyle
                                      }),
                                  Belt_Array.mapWithIndex(selectedFiles, (function (index, file) {
                                          return JsxRuntime.jsxs("div", {
                                                      children: [
                                                        JsxRuntime.jsx("div", {
                                                              children: JsxRuntime.jsx("span", {
                                                                    children: file.name,
                                                                    style: fileNameStyle
                                                                  }),
                                                              style: settingLabelContainerStyle
                                                            }),
                                                        JsxRuntime.jsx("button", {
                                                              children: "Remove",
                                                              style: removeButtonStyle,
                                                              onClick: (function (param) {
                                                                  var filtered = Js_array.filteri((function (param, i) {
                                                                          return i !== index;
                                                                        }), selectedFiles);
                                                                  onSelectedFilesChange(filtered);
                                                                })
                                                            })
                                                      ],
                                                      style: settingRowStyle
                                                    }, String(index));
                                        }))
                                ],
                                style: sectionStyle
                              }),
                          JsxRuntime.jsx("div", {
                                children: JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("button", {
                                              children: "Stitch spectrum",
                                              style: flexButtonStyle,
                                              onClick: (function (param) {
                                                  handleStitch();
                                                })
                                            }),
                                        JsxRuntime.jsx("button", {
                                              children: "Clear",
                                              style: transparentButtonStyle,
                                              onClick: (function (param) {
                                                  handleClear();
                                                })
                                            })
                                      ],
                                      style: buttonRowStyle
                                    }),
                                style: sectionStyle
                              })
                        ]
                      }) : null
              ]
            });
        break;
    case "visualizer" :
        tmp = JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      style: getStatusDotStyle(isConnected && isDeviceConnected)
                                    }),
                                JsxRuntime.jsx("span", {
                                      children: isConnected ? (
                                          isDeviceConnected ? "Connected to server and device" : "Connected to server but device not connected"
                                        ) : "Disconnected",
                                      style: statusTextStyle
                                    })
                              ],
                              style: connectionStatusStyle
                            }),
                        isConnected ? JsxRuntime.jsx("button", {
                                children: isPaused ? "Resume" : "Pause",
                                style: getPauseButtonStyle(isPaused),
                                onClick: (function (param) {
                                    onPauseToggle();
                                  })
                              }) : null
                      ],
                      style: connectionStatusContainerStyle
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Source",
                              style: sectionTitleStyle
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("span", {
                                              children: "RTL-SDR v4",
                                              style: settingLabelStyle
                                            }),
                                        JsxRuntime.jsx(make$1, {
                                              title: "RTL-SDR v4",
                                              content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                                            })
                                      ],
                                      style: settingLabelContainerStyle
                                    }),
                                JsxRuntime.jsx("span", {
                                      children: isConnected && isDeviceConnected ? "Active" : "Unavailable",
                                      style: settingValueStyle
                                    })
                              ],
                              style: settingRowStyle
                            })
                      ],
                      style: sectionStyle
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Signal areas of interest",
                              style: sectionTitleStyle
                            }),
                        JsxRuntime.jsx(make, {
                              label: "A",
                              minFreq: 0.0,
                              maxFreq: 4.75,
                              visibleMin: 0.0,
                              visibleMax: 3.2,
                              isActive: activeSignalArea === "A",
                              onActivate: (function () {
                                  onSignalAreaChange("A");
                                }),
                              onRangeChange: handleAreaARangeChange
                            }),
                        JsxRuntime.jsx(make, {
                              label: "B",
                              minFreq: 24.15,
                              maxFreq: 30.0,
                              visibleMin: 26.0,
                              visibleMax: 28.2,
                              isActive: activeSignalArea === "B",
                              onActivate: (function () {
                                  onSignalAreaChange("B");
                                }),
                              onRangeChange: handleAreaBRangeChange
                            })
                      ],
                      style: sectionStyle
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Signal kind",
                              style: sectionTitleStyle
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("span", {
                                              children: "N-APT",
                                              style: settingLabelStyle
                                            }),
                                        JsxRuntime.jsx(make$1, {
                                              title: "N-APT",
                                              content: "NOAA Automatic Picture Transmission - Weather satellite imagery transmitted in analog format."
                                            })
                                      ],
                                      style: settingLabelContainerStyle
                                    }),
                                JsxRuntime.jsx("span", {
                                      children: "Active",
                                      style: settingValueStyle
                                    })
                              ],
                              style: settingRowStyle
                            })
                      ],
                      style: sectionStyle
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Signal display",
                              style: sectionTitleStyle
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("span", {
                                              children: "FFT Size",
                                              style: settingLabelStyle
                                            }),
                                        JsxRuntime.jsx(make$1, {
                                              title: "FFT Size",
                                              content: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                                            })
                                      ],
                                      style: settingLabelContainerStyle
                                    }),
                                JsxRuntime.jsxs("select", {
                                      children: [
                                        JsxRuntime.jsx("option", {
                                              children: "8192",
                                              value: "8192"
                                            }),
                                        JsxRuntime.jsx("option", {
                                              children: "16384",
                                              value: "16384"
                                            }),
                                        JsxRuntime.jsx("option", {
                                              children: "32768",
                                              value: "32768"
                                            }),
                                        JsxRuntime.jsx("option", {
                                              children: "65536",
                                              value: "65536"
                                            }),
                                        JsxRuntime.jsx("option", {
                                              children: "103432",
                                              value: "103432"
                                            }),
                                        JsxRuntime.jsx("option", {
                                              children: "131072",
                                              value: "131072"
                                            }),
                                        JsxRuntime.jsx("option", {
                                              children: "262144",
                                              value: "262144"
                                            })
                                      ],
                                      style: settingSelectStyle,
                                      value: String(match[0]),
                                      onChange: (function (e) {
                                          var target = e.target;
                                          var value = Belt_Option.getWithDefault(Belt_Int.fromString(target.value), 103432);
                                          setFftSize(function (param) {
                                                return value;
                                              });
                                        })
                                    })
                              ],
                              style: settingRowStyle
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("span", {
                                              children: "FFT Window",
                                              style: settingLabelStyle
                                            }),
                                        JsxRuntime.jsx(make$1, {
                                              title: "FFT Window",
                                              content: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."
                                            })
                                      ],
                                      style: settingLabelContainerStyle
                                    }),
                                JsxRuntime.jsxs("select", {
                                      children: [
                                        JsxRuntime.jsx("option", {
                                              children: "Rectangular",
                                              value: "Rectangular"
                                            }),
                                        JsxRuntime.jsx("option", {
                                              children: "Blackman",
                                              value: "Blackman"
                                            }),
                                        JsxRuntime.jsx("option", {
                                              children: "Nuttall",
                                              value: "Nuttall"
                                            })
                                      ],
                                      style: settingSelectStyle,
                                      value: match$1[0],
                                      onChange: (function (e) {
                                          var target = e.target;
                                          setFftWindow(function (param) {
                                                return target.value;
                                              });
                                        })
                                    })
                              ],
                              style: settingRowStyle
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("span", {
                                              children: "FFT Frame Rate",
                                              style: settingLabelStyle
                                            }),
                                        JsxRuntime.jsx(make$1, {
                                              title: "FFT Frame Rate",
                                              content: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit."
                                            })
                                      ],
                                      style: settingLabelContainerStyle
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("input", {
                                              style: settingInputStyle,
                                              max: "120",
                                              min: "1",
                                              type: "number",
                                              value: String(match$2[0]),
                                              onChange: (function (e) {
                                                  var target = e.target;
                                                  var value = Belt_Option.getWithDefault(Belt_Int.fromString(target.value), 1);
                                                  var clamped = Math.max(1, Math.min(120, value));
                                                  setFftFrameRate(function (param) {
                                                        return clamped;
                                                      });
                                                })
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "fps",
                                              style: fpsTextStyle
                                            })
                                      ],
                                      style: flexGapStyle
                                    })
                              ],
                              style: settingRowStyle
                            })
                      ],
                      style: sectionStyle
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Source Settings",
                              style: sectionTitleStyle
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("span", {
                                              children: "PPM",
                                              style: settingLabelStyle
                                            }),
                                        JsxRuntime.jsx(make$1, {
                                              title: "PPM Correction",
                                              content: "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit."
                                            })
                                      ],
                                      style: settingLabelContainerStyle
                                    }),
                                JsxRuntime.jsx("span", {
                                      children: "1",
                                      style: settingValueStyle
                                    })
                              ],
                              style: settingRowStyle
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("span", {
                                              children: "Gain",
                                              style: settingLabelStyle
                                            }),
                                        JsxRuntime.jsx(make$1, {
                                              title: "Gain Setting",
                                              content: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur."
                                            })
                                      ],
                                      style: settingLabelContainerStyle
                                    }),
                                JsxRuntime.jsx("span", {
                                      children: "+49.06dB",
                                      style: settingValueStyle
                                    })
                              ],
                              style: settingRowStyle
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("span", {
                                              children: "Bandwidth",
                                              style: settingLabelStyle
                                            }),
                                        JsxRuntime.jsx(make$1, {
                                              title: "Bandwidth",
                                              content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum."
                                            })
                                      ],
                                      style: settingLabelContainerStyle
                                    }),
                                JsxRuntime.jsx("span", {
                                      children: "3.2MHz (max)",
                                      style: settingValueStyle
                                    })
                              ],
                              style: settingRowStyle
                            })
                      ],
                      style: sectionStyle
                    })
              ]
            });
        break;
    default:
      tmp = null;
  }
  return JsxRuntime.jsxs("aside", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "Live N-APT visualizer",
                              style: getTabStyle(activeTab === "visualizer"),
                              onClick: (function (param) {
                                  onTabChange("visualizer");
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "N-APT stitcher & I/Q replay",
                              style: getTabStyle(activeTab === "stitcher"),
                              onClick: (function (param) {
                                  onTabChange("stitcher");
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "N-APT live deep analysis",
                              style: getTabStyle(activeTab === "analysis"),
                              onClick: (function (param) {
                                  onTabChange("analysis");
                                })
                            })
                      ],
                      style: tabContainerStyle
                    }),
                tmp
              ],
              style: sidebarContainerStyle
            });
}

var make$2 = Sidebar;

export {
  FrequencyRangeSlider ,
  InfoPopover ,
  make$2 as make,
}
/* make Not a pure module */
