// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Js_math from "rescript/lib/es6/js_math.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";
import * as JsxRuntime from "react/jsx-runtime";

function width(prim) {
  return prim.width;
}

function height(prim) {
  return prim.height;
}

function setWidth(prim0, prim1) {
  prim0.width = prim1;
}

function setHeight(prim0, prim1) {
  prim0.height = prim1;
}

var CanvasOps = {
  width: width,
  height: height,
  setWidth: setWidth,
  setHeight: setHeight
};

var Canvas2D = {};

function fromJson(json) {
  var obj = Js_json.decodeObject(json);
  if (obj === undefined) {
    return {
            waveform: undefined,
            waterfall: undefined
          };
  }
  var v = Js_dict.get(obj, "waveform");
  var waveform;
  if (v !== undefined) {
    var arr = Js_json.decodeArray(v);
    waveform = arr !== undefined ? Belt_Array.keepMap(arr, (function (v) {
              var n = Js_json.decodeNumber(v);
              if (n !== undefined) {
                return n;
              }
              
            })) : undefined;
  } else {
    waveform = undefined;
  }
  var v$1 = Js_dict.get(obj, "waterfall");
  var waterfall;
  if (v$1 !== undefined) {
    var arr$1 = Js_json.decodeArray(v$1);
    waterfall = arr$1 !== undefined ? Belt_Array.keepMap(arr$1, (function (v) {
              var n = Js_json.decodeNumber(v);
              if (n !== undefined) {
                return n | 0;
              }
              
            })) : undefined;
  } else {
    waterfall = undefined;
  }
  return {
          waveform: waveform,
          waterfall: waterfall
        };
}

var SpectrumData = {
  fromJson: fromJson
};

var targetFrameTime = 1000.0 / 30.0;

function formatFreq(freq) {
  if (freq < 1.0) {
    return (freq * 1000.0).toFixed(0) + "kHz";
  } else {
    return freq.toFixed(2) + "MHz";
  }
}

function dbToY(db, minDb, maxDb, spectrumHeight) {
  var normalized = (db - minDb) / (maxDb - minDb);
  var clamped = Math.max(0.0, Math.min(1.0, normalized));
  return spectrumHeight - 40.0 - clamped * (spectrumHeight - 60.0);
}

function getWaterfallColor(intensity) {
  if (intensity < 0.33) {
    var t = intensity * 3.0;
    return [
            0,
            Js_math.floor_int(t * 255.0),
            Js_math.floor_int(255.0 - t * 255.0)
          ];
  }
  if (intensity < 0.66) {
    var t$1 = (intensity - 0.33) * 3.0;
    return [
            Js_math.floor_int(t$1 * 255.0),
            255,
            0
          ];
  }
  var t$2 = (intensity - 0.66) * 3.0;
  return [
          255,
          Js_math.floor_int(255.0 - t$2 * 255.0),
          0
        ];
}

function SpectrumVisualizer(props) {
  var isPaused = props.isPaused;
  var activeSignalArea = props.activeSignalArea;
  var frequencyRange = props.frequencyRange;
  var data = props.data;
  var spectrumCanvasRef = React.useRef(null);
  var waterfallCanvasRef = React.useRef(null);
  var spectrumCtxRef = React.useRef(undefined);
  var waterfallCtxRef = React.useRef(undefined);
  var dataRef = React.useRef(data);
  var waterfallDataRef = React.useRef([]);
  var frequencyRangeRef = React.useRef(frequencyRange);
  var activeSignalAreaRef = React.useRef(activeSignalArea);
  var isPausedRef = React.useRef(isPaused);
  var animationRef = React.useRef(undefined);
  var lastDrawTimeRef = React.useRef(0.0);
  React.useEffect((function () {
          frequencyRangeRef.current = frequencyRange;
        }), [frequencyRange]);
  React.useEffect((function () {
          activeSignalAreaRef.current = activeSignalArea;
        }), [activeSignalArea]);
  React.useEffect((function () {
          isPausedRef.current = isPaused;
        }), [isPaused]);
  var drawSpectrum = function (spectrumCtx, spectrumCanvas, currentData) {
    var spectrumWidth = spectrumCanvas.width;
    var spectrumHeight = spectrumCanvas.height;
    spectrumCtx.fillStyle = "#0a0a0a";
    spectrumCtx.fillRect(0.0, 0.0, spectrumWidth, spectrumHeight);
    var waveform = currentData.waveform;
    if (waveform === undefined) {
      return ;
    }
    if (waveform.length === 0) {
      return ;
    }
    spectrumCtx.strokeStyle = "rgba(100, 200, 255, 0.1)";
    spectrumCtx.lineWidth = 1.0;
    var dbGridLines = [
      -80.0,
      -60.0,
      -40.0,
      -20.0,
      0.0,
      20.0
    ];
    Belt_Array.forEach(dbGridLines, (function (db) {
            var y = dbToY(db, -80.0, 20.0, spectrumHeight);
            spectrumCtx.beginPath();
            spectrumCtx.moveTo(40.0, y);
            spectrumCtx.lineTo(spectrumWidth - 40.0, y);
            spectrumCtx.stroke();
          }));
    for(var i = 0; i <= 10; ++i){
      var x = 40.0 + i * (spectrumWidth - 80.0) / 10.0;
      spectrumCtx.beginPath();
      spectrumCtx.moveTo(x, 20.0);
      spectrumCtx.lineTo(x, spectrumHeight - 40.0);
      spectrumCtx.stroke();
    }
    var len = waveform.length;
    var plotWidth = spectrumWidth - 80.0;
    var binStep = plotWidth / len;
    spectrumCtx.beginPath();
    spectrumCtx.moveTo(40.0, spectrumHeight - 40.0);
    for(var i$1 = 0; i$1 < len; ++i$1){
      var x$1 = 40.0 + i$1 * binStep;
      var y = dbToY(Caml_array.get(waveform, i$1), -80.0, 20.0, spectrumHeight);
      spectrumCtx.lineTo(x$1, y);
    }
    spectrumCtx.lineTo(40.0 + plotWidth, spectrumHeight - 40.0);
    spectrumCtx.closePath();
    spectrumCtx.fillStyle = "rgba(0, 100, 255, 0.3)";
    spectrumCtx.fill();
    spectrumCtx.beginPath();
    spectrumCtx.strokeStyle = "#00d4ff";
    spectrumCtx.lineWidth = 1.5;
    spectrumCtx.lineJoin = "round";
    spectrumCtx.lineCap = "round";
    for(var i$2 = 0; i$2 < len; ++i$2){
      var x$2 = 40.0 + i$2 * binStep;
      var y$1 = dbToY(Caml_array.get(waveform, i$2), -80.0, 20.0, spectrumHeight);
      if (i$2 === 0) {
        spectrumCtx.moveTo(x$2, y$1);
      } else {
        spectrumCtx.lineTo(x$2, y$1);
      }
    }
    spectrumCtx.stroke();
    spectrumCtx.fillStyle = "#666";
    spectrumCtx.font = "16px JetBrains Mono";
    spectrumCtx.textAlign = "right";
    var dbMarkers = [
      -80.0,
      -60.0,
      -40.0,
      -20.0,
      0.0,
      20.0
    ];
    Belt_Array.forEach(dbMarkers, (function (db) {
            var y = dbToY(db, -80.0, 20.0, spectrumHeight);
            spectrumCtx.fillText(db.toString(), 35.0, y + 3.0);
          }));
    var currentFreqRange = frequencyRangeRef.current;
    var minFreq = currentFreqRange.min;
    var maxFreq = currentFreqRange.max;
    var midFreq = (minFreq + maxFreq) / 2.0;
    spectrumCtx.fillStyle = "#e6e6e6";
    spectrumCtx.font = "16px JetBrains Mono";
    spectrumCtx.textAlign = "left";
    spectrumCtx.fillText(formatFreq(minFreq), 40.0, spectrumHeight - 15.0);
    spectrumCtx.textAlign = "right";
    spectrumCtx.fillText(formatFreq(maxFreq), spectrumWidth - 40.0, spectrumHeight - 15.0);
    spectrumCtx.fillStyle = "#ffffff";
    spectrumCtx.font = "bold 28px JetBrains Mono";
    spectrumCtx.textAlign = "center";
    spectrumCtx.fillText(formatFreq(midFreq), spectrumWidth / 2.0, spectrumHeight - 8.0);
  };
  var drawFrame = function () {
    var match = spectrumCtxRef.current;
    var match$1 = waterfallCtxRef.current;
    if (match === undefined) {
      return ;
    }
    if (match$1 === undefined) {
      return ;
    }
    var match$2 = spectrumCanvasRef.current;
    var match$3 = waterfallCanvasRef.current;
    if (match$2 == null) {
      return ;
    }
    if (match$3 == null) {
      return ;
    }
    var currentData = fromJson(Belt_Option.getWithDefault(dataRef.current, null));
    drawSpectrum(Caml_option.valFromOption(match), match$2, currentData);
    var waterfallCtx = Caml_option.valFromOption(match$1);
    var waterfallWidth = match$3.width;
    var waterfallHeight = match$3.height;
    var match$4 = currentData.waterfall;
    var match$5 = isPausedRef.current;
    if (match$4 === undefined) {
      return ;
    }
    if (match$5) {
      return ;
    }
    if (match$4.length === 0) {
      return ;
    }
    waterfallDataRef.current = Belt_Array.concat([match$4], waterfallDataRef.current);
    if (waterfallDataRef.current.length > 200) {
      waterfallDataRef.current = Belt_Array.slice(waterfallDataRef.current, 0, 200);
    }
    var imgData = waterfallCtx.createImageData(waterfallWidth, waterfallHeight);
    var imgDataArray = imgData.data;
    var rows = waterfallDataRef.current;
    var rowHeight = waterfallHeight / 200;
    for(var r = 0 ,r_finish = rows.length; r < r_finish; ++r){
      var row = Caml_array.get(rows, r);
      var y = Js_math.floor_int(r * rowHeight);
      var nextY = Js_math.floor_int((r + 1 | 0) * rowHeight);
      for(var yPixel = y; yPixel < nextY; ++yPixel){
        if (yPixel < waterfallHeight) {
          for(var i = 0 ,i_finish = row.length; i < i_finish; ++i){
            var x = Js_math.floor_int(i / row.length * waterfallWidth);
            var intensity = Caml_array.get(row, i) / 255.0;
            var match$6 = getWaterfallColor(intensity);
            var bVal = match$6[2];
            var gVal = match$6[1];
            var rVal = match$6[0];
            var colWidth = Js_math.ceil_int(waterfallWidth / row.length);
            for(var xPixel = x ,xPixel_finish = x + colWidth | 0; xPixel < xPixel_finish; ++xPixel){
              if (xPixel < waterfallWidth) {
                var index = ((Math.imul(yPixel, waterfallWidth) + xPixel | 0) << 2);
                imgDataArray[index] = rVal;
                imgDataArray[index + 1 | 0] = gVal;
                imgDataArray[index + 2 | 0] = bVal;
                imgDataArray[index + 3 | 0] = 255;
              }
              
            }
          }
        }
        
      }
    }
    waterfallCtx.putImageData(imgData, 0, 0);
  };
  var animate = function () {
    var currentTime = performance.now();
    var timeSinceLastDraw = currentTime - lastDrawTimeRef.current;
    if (timeSinceLastDraw >= targetFrameTime) {
      lastDrawTimeRef.current = currentTime;
      drawFrame();
    }
    var currentData = dataRef.current;
    var hasData;
    if (currentData !== undefined) {
      var parsed = fromJson(currentData);
      var match = parsed.waveform;
      var match$1 = parsed.waterfall;
      hasData = match !== undefined ? true : match$1 !== undefined;
    } else {
      hasData = false;
    }
    if (hasData) {
      animationRef.current = globalThis.requestAnimationFrame(animate);
    } else {
      animationRef.current = undefined;
    }
  };
  var startAnimation = function () {
    var match = animationRef.current;
    if (match !== undefined) {
      return drawFrame();
    } else {
      animationRef.current = globalThis.requestAnimationFrame(animate);
      return ;
    }
  };
  React.useEffect((function () {
          dataRef.current = data;
          if (data !== undefined) {
            startAnimation();
          }
          
        }), [data]);
  React.useEffect((function () {
          frequencyRangeRef.current = frequencyRange;
          drawFrame();
        }), [frequencyRange]);
  React.useEffect((function () {
          var match = spectrumCanvasRef.current;
          var match$1 = waterfallCanvasRef.current;
          if (match == null) {
            return ;
          }
          if (match$1 == null) {
            return ;
          }
          var ctx = match.getContext("2d");
          var spectrumCtx = (ctx == null) ? PervasivesU.failwith("Failed to get 2d context for spectrum canvas") : ctx;
          var ctx$1 = match$1.getContext("2d");
          var waterfallCtx = (ctx$1 == null) ? PervasivesU.failwith("Failed to get 2d context for waterfall canvas") : ctx$1;
          spectrumCtxRef.current = Caml_option.some(spectrumCtx);
          waterfallCtxRef.current = Caml_option.some(waterfallCtx);
          var dpr = globalThis.devicePixelRatio();
          var resizeCanvases = function () {
            var match$2 = match.parentElement;
            var match$3 = match$1.parentElement;
            if (match$2 == null) {
              return ;
            }
            if (match$3 == null) {
              return ;
            }
            var spectrumWidth = match$2.clientWidth();
            var spectrumHeight = match$2.clientHeight();
            var waterfallWidth = match$3.clientWidth();
            var waterfallHeight = match$3.clientHeight();
            var prim1 = Js_math.floor_int(spectrumWidth * dpr);
            match.width = prim1;
            var prim1$1 = Js_math.floor_int(spectrumHeight * dpr);
            match.height = prim1$1;
            var prim1$2 = Js_math.floor_int(waterfallWidth * dpr);
            match$1.width = prim1$2;
            var prim1$3 = Js_math.floor_int(waterfallHeight * dpr);
            match$1.height = prim1$3;
          };
          resizeCanvases();
          window.addEventListener("resize", resizeCanvases);
          return (function () {
                    window.removeEventListener("resize", resizeCanvases);
                    var id = animationRef.current;
                    if (id !== undefined) {
                      globalThis.cancelAnimationFrame(id);
                    }
                    animationRef.current = undefined;
                  });
        }), []);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Spectrum",
                              className: "text-[11px] text-[#555] uppercase tracking-wider mb-2 flex items-center gap-2 after:content-['/'] after:text-[#444]"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("canvas", {
                                    ref: Caml_option.some(spectrumCanvasRef),
                                    className: "w-full h-full block"
                                  }),
                              className: "flex-1 relative bg-[#0a0a0a] border border-[#1a1a1a] rounded overflow-hidden"
                            })
                      ],
                      className: "flex-[2] flex flex-col relative min-h-0"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Waterfall",
                              className: "text-[11px] text-[#555] uppercase tracking-wider mb-2 flex items-center gap-2 after:content-['/'] after:text-[#444]"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("canvas", {
                                    ref: Caml_option.some(waterfallCanvasRef),
                                    className: "w-full h-full block"
                                  }),
                              className: "flex-1 relative bg-[#0a0a0a] border border-[#1a1a1a] rounded overflow-hidden"
                            })
                      ],
                      className: "flex-1 flex flex-col relative min-h-0"
                    })
              ],
              className: "flex-1 flex flex-col bg-[#0a0a0a] relative overflow-hidden p-5 gap-5"
            });
}

var maxWaterfallRows = 200;

var targetFPS = 30.0;

var make = SpectrumVisualizer;

export {
  CanvasOps ,
  Canvas2D ,
  SpectrumData ,
  maxWaterfallRows ,
  targetFPS ,
  targetFrameTime ,
  formatFreq ,
  dbToY ,
  getWaterfallColor ,
  make ,
}
/* react Not a pure module */
