// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_math from "rescript/lib/es6/js_math.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";
import * as Js_typed_array from "rescript/lib/es6/js_typed_array.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as Sdr_wasmJs from "../sdr_wasm/sdr_wasm.js";
import Sdr_wasmJs$1 from "../sdr_wasm/sdr_wasm.js";

function width(prim) {
  return prim.width;
}

function height(prim) {
  return prim.height;
}

function setWidth(prim0, prim1) {
  prim0.width = prim1;
}

function setHeight(prim0, prim1) {
  prim0.height = prim1;
}

var CanvasOps = {
  width: width,
  height: height,
  setWidth: setWidth,
  setHeight: setHeight
};

var Canvas2D = {};

function init(prim) {
  return Sdr_wasmJs$1();
}

function createStitcher(prim0, prim1, prim2) {
  return new Sdr_wasmJs.SpectrumStitcher(prim0, prim1, prim2);
}

var SdrWasm = {
  init: init,
  createStitcher: createStitcher
};

function formatFreq(freq) {
  var freqMHz = freq / 1e6;
  if (Math.abs(freqMHz) < 1.0) {
    return (freqMHz * 1000.0).toFixed(0) + "kHz";
  } else {
    return freqMHz.toFixed(2) + "MHz";
  }
}

function parseFrequency(filename) {
  var regex = /iq_(\\d+\\.?\\d*)([kM]Hz)/;
  var result = regex.exec(filename);
  if (result === null) {
    return ;
  }
  var valueStr = Caml_array.get(result, 1);
  var unitStr = Caml_array.get(result, 2);
  if (valueStr == null) {
    return ;
  }
  if (unitStr == null) {
    return ;
  }
  var value;
  try {
    value = Number(valueStr);
  }
  catch (exn){
    return ;
  }
  if (unitStr === "MHz") {
    return value * 1e6;
  } else {
    return value * 1e3;
  }
}

function binData(frequencies, powerDb, targetBins) {
  var len = frequencies.length;
  if (len <= targetBins) {
    return [
            frequencies,
            powerDb
          ];
  }
  var binSize = Js_math.ceil_int(len / targetBins);
  var binnedFreqs = new Float64Array(targetBins);
  var binnedPower = new Float32Array(targetBins);
  for(var i = 0; i < targetBins; ++i){
    var startIdx = Math.imul(i, binSize);
    var endIdx = Math.min(startIdx + binSize | 0, len);
    var freqSum = 0.0;
    var powerSum = 0.0;
    var count = 0;
    for(var j = startIdx; j < endIdx; ++j){
      freqSum = freqSum + frequencies[j];
      powerSum = powerSum + Math.pow(10.0, powerDb[j] / 10.0);
      count = count + 1 | 0;
    }
    if (count > 0) {
      binnedFreqs[i] = freqSum / count;
      binnedPower[i] = 10.0 * Math.log10(powerSum / count);
    }
    
  }
  return [
          binnedFreqs,
          binnedPower
        ];
}

function smoothData(powerDb, windowSize) {
  var len = powerDb.length;
  var smoothed = new Float32Array(len);
  var halfWindow = windowSize / 2 | 0;
  for(var i = 0; i < len; ++i){
    var sum = 0.0;
    var count = 0;
    var startJ = Math.max(0, i - halfWindow | 0);
    var endJ = Math.min(len - 1 | 0, i + halfWindow | 0);
    for(var j = startJ; j <= endJ; ++j){
      sum = sum + Math.pow(10.0, powerDb[j] / 10.0);
      count = count + 1 | 0;
    }
    if (count > 0) {
      smoothed[i] = 10.0 * Math.log10(sum / count);
    }
    
  }
  return smoothed;
}

function processSpectrum(frequencies, powerDb) {
  var match = binData(frequencies, powerDb, 2048);
  var smoothedPower = smoothData(match[1], 5);
  return [
          match[0],
          smoothedPower
        ];
}

function dbToY(db, minDb, maxDb, height) {
  var normalized = (db - minDb) / (maxDb - minDb);
  var clamped = Math.max(0.0, Math.min(1.0, normalized));
  return height - 40.0 - clamped * (height - 60.0);
}

function plotSpectrum(ctx, canvas, frequencies, powerDb) {
  var len = frequencies.length;
  if (len === 0) {
    return ;
  }
  var width = canvas.width;
  var height = canvas.height;
  ctx.fillStyle = "#0a0a0a";
  ctx.fillRect(0.0, 0.0, width, height);
  var freqMin = frequencies[0];
  var freqMax = frequencies[0];
  for(var i = 1; i < len; ++i){
    var freq = frequencies[i];
    if (freq < freqMin) {
      freqMin = freq;
    }
    if (freq > freqMax) {
      freqMax = freq;
    }
    
  }
  ctx.strokeStyle = "rgba(100, 200, 255, 0.1)";
  ctx.lineWidth = 1.0;
  var dbMarkers = [
    -120.0,
    -100.0,
    -80.0,
    -60.0,
    -40.0,
    -20.0,
    0.0,
    20.0
  ];
  Belt_Array.forEach(dbMarkers, (function (db) {
          var y = dbToY(db, -120.0, 20.0, height);
          ctx.beginPath();
          ctx.moveTo(40.0, y);
          ctx.lineTo(width - 40.0, y);
          ctx.stroke();
        }));
  for(var i$1 = 0; i$1 <= 10; ++i$1){
    var x = 40.0 + i$1 * (width - 80.0) / 10.0;
    ctx.beginPath();
    ctx.moveTo(x, 20.0);
    ctx.lineTo(x, height - 40.0);
    ctx.stroke();
  }
  var plotWidth = width - 80.0;
  ctx.beginPath();
  ctx.moveTo(40.0, height);
  for(var i$2 = 0; i$2 < len; ++i$2){
    var freq$1 = frequencies[i$2];
    var power = powerDb[i$2];
    var x$1 = 40.0 + (freq$1 - freqMin) / (freqMax - freqMin) * plotWidth;
    var y = dbToY(power, -120.0, 20.0, height);
    ctx.lineTo(x$1, y);
  }
  ctx.lineTo(40.0 + plotWidth, height);
  ctx.closePath();
  ctx.fillStyle = "rgba(0, 100, 255, 0.3)";
  ctx.fill();
  ctx.beginPath();
  ctx.strokeStyle = "#00d4ff";
  ctx.lineWidth = 1.5;
  ctx.lineJoin = "round";
  ctx.lineCap = "round";
  for(var i$3 = 0; i$3 < len; ++i$3){
    var freq$2 = frequencies[i$3];
    var power$1 = powerDb[i$3];
    var x$2 = 40.0 + (freq$2 - freqMin) / (freqMax - freqMin) * plotWidth;
    var y$1 = dbToY(power$1, -120.0, 20.0, height);
    if (i$3 === 0) {
      ctx.moveTo(x$2, y$1);
    } else {
      ctx.lineTo(x$2, y$1);
    }
  }
  ctx.stroke();
  ctx.fillStyle = "#666";
  ctx.font = "16px JetBrains Mono";
  ctx.textAlign = "right";
  Belt_Array.forEach(dbMarkers, (function (db) {
          var y = dbToY(db, -120.0, 20.0, height);
          ctx.fillText(db.toString(), 35.0, y + 3.0);
        }));
  var midFreq = (freqMin + freqMax) / 2.0;
  ctx.fillStyle = "#e6e6e6";
  ctx.font = "16px JetBrains Mono";
  ctx.textAlign = "left";
  ctx.fillText(formatFreq(freqMin), 40.0, height - 15.0);
  ctx.textAlign = "right";
  ctx.fillText(formatFreq(freqMax), width - 40.0, height - 15.0);
  ctx.fillStyle = "#ffffff";
  ctx.font = "bold 28px JetBrains Mono";
  ctx.textAlign = "center";
  ctx.fillText(formatFreq(midFreq), width / 2.0, height - 8.0);
}

function StitcherVisualizer(props) {
  var onStitch = props.onStitch;
  var selectedFiles = props.selectedFiles;
  var canvasRef = React.useRef(null);
  var ctxRef = React.useRef(undefined);
  var processedDataRef = React.useRef(undefined);
  var redrawTriggerRef = React.useRef(0);
  var handlerRegisteredRef = React.useRef(false);
  var stitchFilesRef = React.useRef(function () {
        
      });
  var match = React.useState(function () {
        return "Select files to begin stitching";
      });
  var setStatus = match[1];
  var match$1 = React.useState(function () {
        return 0.0;
      });
  var setProcessingTime = match$1[1];
  var match$2 = React.useState(function () {
        return 0;
      });
  var setNumPoints = match$2[1];
  var match$3 = React.useState(function () {
        return "0 - 0 MHz";
      });
  var setFreqRange = match$3[1];
  var match$4 = React.useState(function () {
        return false;
      });
  var setShowResults = match$4[1];
  var match$5 = React.useState(function () {
        return false;
      });
  var setIsInitialized = match$5[1];
  var isInitialized = match$5[0];
  React.useEffect((function () {
          if (!handlerRegisteredRef.current) {
            var handler = function () {
              stitchFilesRef.current();
            };
            onStitch(handler);
            handlerRegisteredRef.current = true;
          }
          
        }), [onStitch]);
  React.useEffect((function () {
          var initWasm = async function () {
            try {
              await Sdr_wasmJs$1();
              setIsInitialized(function (param) {
                    return true;
                  });
              return setStatus(function (param) {
                          return "WASM initialized. Select .c64 files.";
                        });
            }
            catch (raw_error){
              var error = Caml_js_exceptions.internalToOCamlException(raw_error);
              var msg = JSON.stringify(error);
              var errorMessage = msg !== undefined ? msg : "Unknown error";
              return setStatus(function (param) {
                          return "Error initializing WASM: " + errorMessage;
                        });
            }
          };
          initWasm();
        }), []);
  React.useEffect((function () {
          var canvas = canvasRef.current;
          if (canvas == null) {
            return ;
          }
          var ctx = canvas.getContext("2d");
          var ctx$1 = (ctx == null) ? PervasivesU.failwith("Failed to get 2d context") : ctx;
          ctxRef.current = Caml_option.some(ctx$1);
          var dpr = globalThis.devicePixelRatio();
          var resizeCanvas = function () {
            var wrapper = canvas.parentElement;
            if (wrapper == null) {
              return ;
            }
            var w = wrapper.clientWidth();
            var h = wrapper.clientHeight();
            var prim1 = Js_math.floor_int(w * dpr);
            canvas.width = prim1;
            var prim1$1 = Js_math.floor_int(h * dpr);
            canvas.height = prim1$1;
            ctx$1.scale(dpr, dpr);
            var match = processedDataRef.current;
            if (match !== undefined) {
              redrawTriggerRef.current = redrawTriggerRef.current + 1 | 0;
              return ;
            }
            
          };
          resizeCanvas();
          window.addEventListener("resize", resizeCanvas);
          return (function () {
                    window.removeEventListener("resize", resizeCanvas);
                  });
        }), []);
  React.useEffect((function () {
          var match = processedDataRef.current;
          var match$1 = ctxRef.current;
          if (match !== undefined && match$1 !== undefined) {
            var canvas = canvasRef.current;
            if (!(canvas == null)) {
              plotSpectrum(Caml_option.valFromOption(match$1), canvas, match[0], match[1]);
            }
            
          }
          
        }), [redrawTriggerRef.current]);
  var stitchFiles = async function () {
    if (isInitialized) {
      if (selectedFiles.length === 0) {
        setStatus(function (param) {
              return "No files selected";
            });
        return ;
      }
      setStatus(function (param) {
            return "Processing...";
          });
      var startTime = performance.now();
      try {
        var stitcher = new Sdr_wasmJs.SpectrumStitcher(262144, 3.2e6, -100.0);
        var validFiles = Belt_Array.keep(selectedFiles, (function (file) {
                return file.name !== "";
              }));
        if (validFiles.length === 0) {
          return setStatus(function (param) {
                      return "No valid files selected";
                    });
        }
        for(var i = 0 ,i_finish = validFiles.length; i < i_finish; ++i){
          var file = Caml_array.get(validFiles, i);
          var name = file.name;
          var centerFreq = parseFrequency(name);
          if (centerFreq !== undefined) {
            setStatus((function(i,name){
                return function (param) {
                  return "Processing " + (i + 1 | 0).toString() + "/" + validFiles.length.toString() + ": " + name + "...";
                }
                }(i,name)));
            var buffer = await file.arrayBuffer();
            var validLength = (Js_math.floor_int(buffer.byteLength / 4.0) << 2);
            var validData = Js_typed_array.$$ArrayBuffer.slice(0, validLength, buffer);
            var iqData = new Float32Array(validData);
            stitcher.add_capture(iqData, centerFreq);
          } else {
            console.warn("Skipping " + name + " - couldn't parse frequency");
          }
        }
        var elapsedTime = performance.now() - startTime;
        var rawFrequencies = stitcher.get_frequencies();
        var rawPowerDb = stitcher.get_power_db();
        var freqRangeResult = stitcher.get_frequency_range();
        var match;
        if (freqRangeResult.length !== 2) {
          match = [
            0.0,
            0.0
          ];
        } else {
          var min = freqRangeResult[0];
          var max = freqRangeResult[1];
          match = [
            min,
            max
          ];
        }
        var maxFreq = match[1];
        var minFreq = match[0];
        var match$1 = processSpectrum(rawFrequencies, rawPowerDb);
        var processedFreqs = match$1[0];
        processedDataRef.current = [
          processedFreqs,
          match$1[1]
        ];
        setNumPoints(function (param) {
              return processedFreqs.length;
            });
        setFreqRange(function (param) {
              return formatFreq(minFreq) + " - " + formatFreq(maxFreq);
            });
        setProcessingTime(function (param) {
              return elapsedTime;
            });
        setShowResults(function (param) {
              return true;
            });
        redrawTriggerRef.current = redrawTriggerRef.current + 1 | 0;
        return setStatus(function (param) {
                    return "✓ Stitching complete! Processed " + selectedFiles.length.toString() + " captures in " + elapsedTime.toString() + " ms";
                  });
      }
      catch (raw_error){
        var error = Caml_js_exceptions.internalToOCamlException(raw_error);
        var msg = JSON.stringify(error);
        var errorMessage = msg !== undefined ? msg : "Unknown error";
        setStatus(function (param) {
              return "Error: " + errorMessage;
            });
        console.error("Stitching error:", error);
        return ;
      }
    } else {
      setStatus(function (param) {
            return "WASM not initialized yet...";
          });
      return ;
    }
  };
  stitchFilesRef.current = (function () {
      stitchFiles();
    });
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                            children: "Stitcher Visualizer",
                            className: "text-[11px] text-[#555] uppercase tracking-wider mb-2 flex items-center gap-2 after:content-['/'] after:text-[#444]"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("div", {
                                    children: match[0],
                                    className: "absolute top-2.5 right-5 font-mono text-xs px-3 py-2 rounded z-10",
                                    style: {
                                      backgroundColor: "rgba(0, 0, 0, 0.8)",
                                      color: isInitialized ? "#0f0" : "#f00"
                                    }
                                  }),
                              JsxRuntime.jsx("canvas", {
                                    ref: Caml_option.some(canvasRef),
                                    className: "w-full h-full block"
                                  })
                            ],
                            className: "flex-1 relative bg-[#0a0a0a] border border-[#1a1a1a] rounded overflow-hidden"
                          }),
                      match$4[0] ? JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: "Frequency Points: " + match$2[0].toString()
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: "Frequency Range: " + match$3[0]
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: "Processing Time: " + match$1[0].toString() + " ms"
                                    })
                              ],
                              className: "bg-[#1a1a1a] p-4 rounded mt-2.5 text-sm font-mono text-[#666]"
                            }) : null
                    ],
                    className: "flex-1 flex flex-col relative min-h-0"
                  }),
              className: "flex-1 flex flex-col bg-[#0a0a0a] relative overflow-hidden p-5 gap-5"
            });
}

var targetBins = 2048;

var smoothingWindow = 5;

var make = StitcherVisualizer;

export {
  CanvasOps ,
  Canvas2D ,
  SdrWasm ,
  targetBins ,
  smoothingWindow ,
  formatFreq ,
  parseFrequency ,
  binData ,
  smoothData ,
  processSpectrum ,
  dbToY ,
  plotSpectrum ,
  make ,
}
/* react Not a pure module */
