/**
 * Main constants index file
 * Exports all constants from their respective modules
 * Explicit exports to prevent Safari circular dependency issues
 */

// Export theme first since other modules depend on it
export { THEME_TOKENS } from "./theme";

// Export components (now depends on theme in same directory)
export {
  MODEL_ROOT_POSITION,
  BRAIN_POSITION,
  BRAIN_SCALE,
  DEFAULT_SPIKE_COUNT,
  DEFAULT_SPIKE_WIDTH,
  DEFAULT_CENTER_SPIKE_BOOST,
  DEFAULT_FLOOR_AMPLITUDE,
  DEFAULT_DECAY_RATE,
  DEFAULT_BASELINE_MODULATION,
  DEFAULT_ENVELOPE_WIDTH,
  DEFAULT_NUM_POINTS,
  STEP_SIZE,
  SLIDER_WRAPPER_STYLE,
  HOTSPOT_SIZE_LARGE,
  HOTSPOT_SIZE_SMALL,
  HOTSPOT_COLOR_LARGE,
  HOTSPOT_COLOR_SMALL,
  HOTSPOT_COLOR_SELECTED,
  HOTSPOT_COLOR_MULTISELECT,
  HOTSPOT_MESH_NAME,
  HOTSPOT_EDIT_SPHERE_SIZE,
  HOTSPOT_EDIT_BUTTON_SIZE,
  HOTSPOT_EDIT_PLANE_SIZE,
  HOTSPOT_CONTROL_PANEL_WIDTH,
  HOTSPOT_CONTROL_PANEL_PADDING,
  MODEL_AMBIENT_LIGHT_INTENSITY,
  MODEL_KEY_LIGHT_INTENSITY,
  MODEL_KEY_LIGHT_POSITION,
  MODEL_FILL_LIGHT_INTENSITY,
  MODEL_FILL_LIGHT_POSITION,
  MODEL_BACK_LIGHT_INTENSITY,
  MODEL_BACK_LIGHT_POSITION,
  MODEL_CAMERA_POSITION,
  MODEL_CAMERA_TARGET,
  MODEL_FOV,
  SPHERE_GEOMETRY_SEGMENTS,
  SPHERE_MARKER_COLOR,
  SPHERE_MARKER_BASE_INTENSITY,
  CONTROL_PANEL_WIDTH,
  POPOVER_WIDTH,
  POPOVER_PADDING,
  INFO_ICON_SIZE,
  POPOVER_Z_INDEX,
  POPOVER_ICON_BACKGROUND,
  POPOVER_ICON_BORDER,
  POPOVER_ICON_COLOR,
  POPOVER_ICON_HOVER_BACKGROUND,
  POPOVER_ICON_HOVER_COLOR,
  POPOVER_BACKGROUND,
  POPOVER_BORDER,
  POPOVER_TITLE_COLOR,
  POPOVER_TEXT_COLOR,
  SIDEBAR_WIDTH,
  SIDEBAR_MIN_WIDTH,
  SIDEBAR_PADDING,
  CONNECTION_STATUS_FLEX,
  PAUSE_BUTTON_FLEX,
  DEFAULT_FFT_SIZE,
  DEFAULT_FFT_WINDOW,
  DEFAULT_FFT_FRAME_RATE,
  FILE_INPUT_ACCEPT,
  VISUALIZER_PADDING,
  VISUALIZER_GAP,
  WATERFALL_HISTORY_LIMIT,
  WATERFALL_HISTORY_MAX,
  SECTION_TITLE_COLOR,
  SECTION_TITLE_AFTER_COLOR,
  CANVAS_BORDER_COLOR,
  RANGE_TRACK_HEIGHT,
  RANGE_TRACK_BACKGROUND,
  RANGE_TRACK_BORDER,
  RANGE_LABELS_COLOR,
  RANGE_LABELS_PADDING,
  RANGE_LABELS_FONT_SIZE,
  STITCHER_BUTTON_STYLE,
  COLORS,
  FONTS,
  SPACING,
} from "./components";

// Export FFT constants (depends on components)
export {
  FFT_GRID_COLOR,
  LINE_COLOR,
  HOLD_COLOR,
  SHADOW_COLOR,
  FFT_TEXT_COLOR,
  FFT_MIN_DB,
  FFT_MAX_DB,
  DB_MARKERS,
  VERTICAL_RANGE,
  FFT_FREQUENCY_RANGES,
  FFT_AREA_MIN,
  FFT_CANVAS_BG,
  FFT_FONT_FAMILY,
  FFT_FONT_SIZE,
  SNAP_HW_RATE_LINE,
  SNAP_HW_RATE_TEXT,
  SNAP_CENTER_LABEL_BG,
  SNAP_CENTER_LABEL_TEXT,
  CENTER_LINE_COLOR,
  OFFSET_TICK_LINE_COLOR,
  OFFSET_TICK_TEXT_COLOR,
  BOUNDARY_LINE_COLOR,
  BOUNDARY_TEXT_COLOR,
} from "./fft";

// Export environment constants
export * from "./env";

// Export shared constants
export * from "./shared";

// Export waterfall constants
export * from "./waterfall";

// Export mock constants
export * from "./mock";
