// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as UseWebSocket from "./hooks/UseWebSocket.res.mjs";
import * as ReactRouterDom from "react-router-dom";
import * as JsxRuntime from "react/jsx-runtime";
import * as SidebarResMjs from "./components/Sidebar.res.mjs";
import * as DrawMockNAPTResMjs from "./components/DrawMockNAPT.res.mjs";
import * as HumanModelViewerResMjs from "./components/HumanModelViewer.res.mjs";
import * as SpectrumVisualizerResMjs from "./components/SpectrumVisualizer.res.mjs";
import * as StitcherVisualizerResMjs from "./components/StitcherVisualizer.res.mjs";

var BrowserRouter = {};

var Routes = {};

var Route = {};

var Link = {};

var ReactRouter = {
  BrowserRouter: BrowserRouter,
  Routes: Routes,
  Route: Route,
  Link: Link
};

var make = SidebarResMjs.make;

var Sidebar = {
  make: make
};

var make$1 = SpectrumVisualizerResMjs.make;

var SpectrumVisualizer = {
  make: make$1
};

var make$2 = StitcherVisualizerResMjs.make;

var StitcherVisualizer = {
  make: make$2
};

var make$3 = DrawMockNAPTResMjs.make;

var DrawMockNAPT = {
  make: make$3
};

var make$4 = HumanModelViewerResMjs.make;

var HumanModelViewer = {
  make: make$4
};

function mainTabToString(tab) {
  switch (tab) {
    case "Spectrum" :
        return "spectrum";
    case "DrawSignal" :
        return "draw-signal";
    case "Model3D" :
        return "3d-model";
    
  }
}

function stringToMainTab(str) {
  switch (str) {
    case "3d-model" :
        return "Model3D";
    case "draw-signal" :
        return "DrawSignal";
    default:
      return "Spectrum";
  }
}

function routeToMainTab(path) {
  switch (path) {
    case "/3d-model" :
        return "Model3D";
    case "/draw-signal" :
        return "DrawSignal";
    default:
      return "Spectrum";
  }
}

function routeToActiveTab(path) {
  switch (path) {
    case "/analysis" :
        return "analysis";
    case "/stitcher" :
        return "stitcher";
    default:
      return "visualizer";
  }
}

function App$AppContent(props) {
  var $$location = ReactRouterDom.useLocation();
  var navigate = ReactRouterDom.useNavigate();
  var mainTab = routeToMainTab($$location.pathname);
  var activeTab = routeToActiveTab($$location.pathname);
  var match = React.useState(function () {
        return "A";
      });
  var setActiveSignalArea = match[1];
  var activeSignalArea = match[0];
  var match$1 = React.useState(function () {
        return {
                min: 0.0,
                max: 3.2
              };
      });
  var setFrequencyRange = match$1[1];
  var frequencyRange = match$1[0];
  var match$2 = React.useState(function () {
        return [];
      });
  var setSelectedFiles = match$2[1];
  var selectedFiles = match$2[0];
  var isVisualizer = activeTab === "visualizer";
  var isStitcher = activeTab === "stitcher";
  var match$3 = UseWebSocket.useWebSocket("ws://localhost:8765", isVisualizer && mainTab === "Spectrum");
  var sendPauseCommand = match$3.sendPauseCommand;
  var sendFrequencyRange = match$3.sendFrequencyRange;
  var data = match$3.data;
  var isPaused = match$3.isPaused;
  var isDeviceConnected = match$3.isDeviceConnected;
  var isConnected = match$3.isConnected;
  var stitchHandlerRef = React.useRef(undefined);
  var handleStitch = React.useCallback((function () {
          var handler = stitchHandlerRef.current;
          if (handler !== undefined) {
            return handler();
          } else {
            console.error("stitchHandlerRef.current is null! Visualizer may not be ready.");
            return ;
          }
        }), []);
  var handleClear = function () {
    setSelectedFiles(function (param) {
          return [];
        });
  };
  var handleSidebarTabChange = function (tab) {
    switch (tab) {
      case "analysis" :
          return navigate("/analysis");
      case "stitcher" :
          return navigate("/stitcher");
      default:
        return navigate("/");
    }
  };
  React.useEffect((function () {
          if (isConnected && mainTab === "Spectrum") {
            sendPauseCommand(!isVisualizer);
          }
          
        }), [
        isVisualizer,
        isConnected,
        mainTab
      ]);
  var handleSignalAreaChange = function (area) {
    if (area !== activeSignalArea) {
      setActiveSignalArea(function (param) {
            return area;
          });
      if (area === "A") {
        return setFrequencyRange(function (param) {
                    return {
                            min: 0.0,
                            max: 3.2
                          };
                  });
      } else if (area === "B") {
        return setFrequencyRange(function (param) {
                    return {
                            min: 26.0,
                            max: 28.2
                          };
                  });
      } else {
        return ;
      }
    }
    
  };
  var handleFrequencyRangeChange = function (range) {
    setFrequencyRange(function (param) {
          return range;
        });
    sendFrequencyRange(range);
  };
  var appContainerStyle = {
    backgroundColor: "#0a0a0a",
    display: "flex",
    height: "100vh",
    width: "100%"
  };
  var mainContentStyle = {
    display: "flex",
    overflow: "hidden",
    flex: "1",
    flexDirection: "column"
  };
  var placeholderContentStyle = {
    color: "#444",
    display: "flex",
    fontSize: "14px",
    alignItems: "center",
    flex: "1",
    justifyContent: "center"
  };
  var tabContainerStyle = {
    backgroundColor: "#0d0d0d",
    borderBottom: "1px solid #1a1a1a",
    display: "flex",
    padding: "0 20px"
  };
  var getTabStyle = function (isActive) {
    return {
            backgroundColor: isActive ? "#1a1a1a" : "transparent",
            border: "none",
            borderBottom: "2px solid " + (
              isActive ? "#00d4ff" : "transparent"
            ),
            color: isActive ? "#00d4ff" : "#666",
            cursor: "pointer",
            fontFamily: "'JetBrains Mono', monospace",
            fontSize: "13px",
            fontWeight: "500",
            padding: "12px 24px",
            transition: "all 0.2s ease",
            userSelect: "none"
          };
  };
  var contentAreaStyle = {
    display: "flex",
    overflow: "hidden",
    flex: "1"
  };
  var renderContent = function () {
    switch (mainTab) {
      case "Spectrum" :
          return JsxRuntime.jsxs(JsxRuntime.Fragment, {
                      children: [
                        JsxRuntime.jsx(make, {
                              isConnected: isConnected,
                              isDeviceConnected: isDeviceConnected,
                              isPaused: isPaused,
                              activeTab: activeTab,
                              onTabChange: handleSidebarTabChange,
                              activeSignalArea: activeSignalArea,
                              onSignalAreaChange: handleSignalAreaChange,
                              onFrequencyRangeChange: handleFrequencyRangeChange,
                              onPauseToggle: (function () {
                                  sendPauseCommand(!isPaused);
                                }),
                              selectedFiles: selectedFiles,
                              onSelectedFilesChange: (function (files) {
                                  setSelectedFiles(function (param) {
                                        return files;
                                      });
                                }),
                              onStitch: handleStitch,
                              onClear: handleClear
                            }),
                        JsxRuntime.jsx("section", {
                              children: isVisualizer ? JsxRuntime.jsx(make$1, {
                                      data: data,
                                      frequencyRange: frequencyRange,
                                      activeSignalArea: activeSignalArea,
                                      isPaused: isPaused
                                    }) : (
                                  isStitcher ? JsxRuntime.jsx(make$2, {
                                          selectedFiles: selectedFiles,
                                          onStitch: (function (handler) {
                                              stitchHandlerRef.current = handler;
                                            }),
                                          onClear: handleClear
                                        }) : JsxRuntime.jsx("div", {
                                          children: "N-APT Live Deep Analysis - Coming Soon",
                                          style: placeholderContentStyle
                                        })
                                ),
                              style: mainContentStyle
                            })
                      ]
                    });
      case "DrawSignal" :
          return JsxRuntime.jsx("section", {
                      children: JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx(make$3, {}),
                            style: {
                              height: "100%",
                              padding: "20px"
                            }
                          }),
                      style: Object.assign({}, mainContentStyle, {
                            overflow: "auto"
                          })
                    });
      case "Model3D" :
          return JsxRuntime.jsx("section", {
                      children: JsxRuntime.jsx(make$4, {}),
                      style: mainContentStyle
                    });
      
    }
  };
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("button", {
                                    children: "Spectrum Analyzer",
                                    style: getTabStyle(mainTab === "Spectrum"),
                                    onClick: (function (param) {
                                        navigate("/");
                                      })
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: "Draw Signal Form",
                                    style: getTabStyle(mainTab === "DrawSignal"),
                                    onClick: (function (param) {
                                        navigate("/draw-signal");
                                      })
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: "3D Human Model",
                                    style: getTabStyle(mainTab === "Model3D"),
                                    onClick: (function (param) {
                                        navigate("/3d-model");
                                      })
                                  })
                            ],
                            style: tabContainerStyle
                          }),
                      JsxRuntime.jsx("div", {
                            children: renderContent(),
                            style: contentAreaStyle
                          })
                    ],
                    style: {
                      display: "flex",
                      height: "100%",
                      width: "100%",
                      flexDirection: "column"
                    }
                  }),
              style: appContainerStyle
            });
}

var AppContent = {
  make: App$AppContent
};

function App(props) {
  return JsxRuntime.jsx(ReactRouterDom.BrowserRouter, {
              children: JsxRuntime.jsx(App$AppContent, {})
            });
}

var make$5 = App;

var $$default = App;

export {
  ReactRouter ,
  Sidebar ,
  SpectrumVisualizer ,
  StitcherVisualizer ,
  DrawMockNAPT ,
  HumanModelViewer ,
  mainTabToString ,
  stringToMainTab ,
  routeToMainTab ,
  routeToActiveTab ,
  AppContent ,
  make$5 as make,
  $$default as default,
}
/* make Not a pure module */
