// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as IndexCss from "./index.css";
import * as AppResMjs from "./App.res.mjs";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

var Client$1 = {};

var ReactDOM = {
  Client: Client$1
};

var _css = IndexCss;

var make = AppResMjs.make;

var App = {
  make: make
};

var rootElement = document.getElementById("root");

if (rootElement == null) {
  console.error("Could not find root element");
} else {
  var root = Client.createRoot(rootElement);
  root.render(JsxRuntime.jsx(React.StrictMode, {
            children: JsxRuntime.jsx(make, {})
          }));
}

export {
  ReactDOM ,
  _css ,
  App ,
}
/* _css Not a pure module */
